### ISSUE TITLE
Audit table index too big with utf8mb4

### ISSUE THREAD

**Issue by kevinboerland** [oroinc/platform#1009]
**Summary**
When installing OroPlatform 4.1.2 I get a `Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes` error when it's trying to create the `oro_audit` table. Because the `idx_oro_audit_transaction` index is too big.

**Steps to reproduce**
1. Have an empty environment with the database configured to use utf8mb4 according to the [installation documention](https://doc.oroinc.com/backend/setup/dev-environment/manual-installation/platform-ce/#change-the-mysql-server-configuration)
2. Configure the doctrine to use utf8mb4 as well just like the docs
3. Install the application

**Actual Result**
Installation is aborted due to not being able to create the database table

**Details about your Environment**
* OroPlatform version: 4.1.2
* PHP version: 7.4.5
* Database version: MySQL 5.7 and MariaDB 10.4
* OS: KDE Neon 5.18 and Ubuntu server 18.04

**Additional Information**
The cause of this bug is pretty simple, the `idx_oro_audit_transaction` consists of 4 varchar fields which all have a length of 255 characters. The index size would be 255 * 4(no. of fields) * 4 byte per character which is 4080 bytes.

Removing the index or changing the charset to something less than 4 bytes per character fixes the issue.
Issue was introduced in this commit: https://github.com/oroinc/platform/commit/28632619398b38375993003e7ae31c4dfd2f843b#diff-3f0e9adaa481c627f909ea01bd50789cR67

**Comment by anyt** [comment]
Thank you for the report.
Internal ticket id #BAP-18992

**Comment by jimohalloran** [comment]
As Roberto Briones points out on slack, the change introduced in 4.1.3 intended to resolve this doesn't.  The migration to add the index runs before the schema change migration.  Need to implement `OrderedMigrationInterface` and use `getOrder` functions to force them to run in the correct order.

**Comment by jimohalloran** [comment]
Upgraded my OroCRM to 4.1.5 today without error.  These migrations now implement `OrderedMigrationInterface` and run in the correct order so this is no longer a problem.  This ticket can be closed.

**Comment by anyt** [comment]
Thank you for the feedback! 👍
