### ISSUE TITLE
ORO Packagist issue

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#1011]
**Summary**  
When performing a composer update or install on platform  composer report an issue with ORO Packagist

![image](https://user-images.githubusercontent.com/794449/80168543-1ec2a600-85b1-11ea-9c65-7f2d8da94682.png)

**Steps to reproduce**  
Looking at the file, there is a big chunk missing at the end.

![image](https://user-images.githubusercontent.com/794449/80170003-f6d54180-85b4-11ea-98e5-1ee6efd15270.png)

**Actual Result**

**Expected Result**  

**Details about your environment**
- OroPlatform version: x.y.z
- PHP version: x.y.z
- Database (MySQL, PostgreSQL) version

**Additional information**

**Comment by sadortun** [comment]
Also,

Could you please add `oro/redis-config` to `packagist.org` ?  

```
  Problem 3
    - The requested package oro/redis-config could not be found in any version, there may be a typo in the package name.
```

Thanks,
Samuel

**Comment by anyt** [comment]
Fixed. 
Thank you for the report, Samuel!

**Comment by sadortun** [comment]
Hi @anyt 

Would you be able to add `oro/redis-config` to `packagist.org` ? It's the only package from the `oro` namespace that is missing. ( At least that prevent performing an install without the `orocrm` repository.

Thanks

**Comment by sadortun** [comment]
Hi Again @anyt 

One more thing !  There is an obselete non-updated package `composer/composer` in the `oro packagist` that should probably be removed.

https://packagist.orocrm.com/?#composer

**Comment by mbessolov** [comment]
@sadortun can you share the full composer.json?

Removing a package from the repository is normally a no go - as it will prevent reinstallation of a few (though very old) versions of the app that depend on it.
I'm not saying that we support or in any form encourage anyone to use it, but killing a package is not good.

**Comment by sadortun** [comment]
@mbessolov I am using the github project for theses tests.

You can test it with `composer self-update --snapshot`

I understand that removing a package is not a good thing, but 
- since the `composer/composer` package was not updated since `2015-04-14`  
- Default behaviour in composer 2.0 have changed, and since the ORO packagist have priority over `packagist.org` YOUR composer package will be used for dependency resolution
` Default behaviour of composer 1.x is to look at all repository for matching version.

My guess is that is `should` be safe to remove it. But it's your call of course ! I only wanted to advise you on the upcoming problem with composer 2.0

Thanks,
Samuel

**Comment by anyt** [comment]
`composer/composer` was used by our package manager that is not supported anymore. It should be safe to remove it. I'll check, thanks for the notice. But it's not related to the composer version installed globally anyway.

As for the composer update speed, consider installing symfony/flex globally. It speeds up composer operations a lot.
```bash
composer global require symfony/flex
```
The team currently working on composer 2.0 compatibility. We have fixed a few related issues recently.

And for the `oro/redis-config` it's a question to Michael. Anyway, you'll not be able to use many other oroplatform extensions without Oro's packagist server in `composer.json`

**Comment by sadortun** [comment]
@anyt  Awesome ! Have a great day !

**Comment by mbessolov** [comment]
@anyt JFYI, symfony/flex is not compatible with Composer 2.0

**Comment by anyt** [comment]
same as oro/platform, but composer 2.0 is not released yet.
symfony flex with composer 1.0 enables parallel download that is the main performance improvement in composer 2.0 afaik, but it also limits symfony/symfony versions in the dependency tree, so it additionally speeds up update and require operations.
with composer 2.0 symfony flex will still be useful for us.
