### ISSUE TITLE
Twig/Extensions is no longer maintained and breaks Opcache Preload

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#1014]
**Summary**  

The dependency https://github.com/twigphp/Twig-extensions is no longer maintained and there is options to migrate to their readme

Currently this extension is breaking PHP 7.4 Opcache preload fonctionality.

**Steps to reproduce**  

**Actual Result**

```
Fatal error</b>:  Cannot redeclare twig_truncate_filter() (previously declared in vendor/twig/extensions/lib/Twig/Extensions/Extension/Text.php:38) in
```

**Expected Result**  

**Details about your environment**
- OroPlatform version:  4.1
- PHP version: 7.4.5

**Additional information**

**Comment by khoatran** [comment]
I've got the same issue

**Comment by anyt** [comment]
We removed twig/extensions dependency in 4.2 LTS version.
