### ISSUE TITLE
Synchronize emails

### ISSUE THREAD

**Issue by Iyadhfaleh** [oroinc/platform#1049]
**Summary**  
An exception threw when synchronizing emails when the subject contains emojis.

![image](https://user-images.githubusercontent.com/3882551/99668273-cb90d300-2a6d-11eb-9f84-ecee4d2beb2d.png)

![image](https://user-images.githubusercontent.com/3882551/99668377-efecaf80-2a6d-11eb-83e5-2696ccba22d6.png)

**Comment by anyt** [comment]
Hi @Iyadhfaleh,
This is sad that you have deleted the default template for the issue report, as it's beneficial for us to understand your setup, to know where the bug should be fixed. We added it for a reason.

Anyway, the scenario that you described looks like a known bug that was already fixed a long time ago. This should not be an issue for the only supported version of the 4.1 LTS.

**Comment by anyt** [comment]
This bug was fixed in 4.1 LTS.

**Comment by Iyadhfaleh** [comment]
@anyt , I upgraded to 4.1.10 but I have the same issue 

` {
            "name": "oro/platform",
            "version": "4.1.10",
            "source": {
                "type": "git",
                "url": "https://github.com/oroinc/platform.git",
                "reference": "3a4873fc8ebb7d51c683269abd89631b184d0ea7"
            }
}`

**Comment by anyt** [comment]
please share the output of the command


```
composer info | grep oro/

**Comment by Iyadhfaleh** [comment]
oro/calendar-bundle                  4.1.8              Calendar bundle for OroPlatform-based applications.
oro/crm                              4.1.0              OroCRM
oro/crm-call-bundle                  4.1.6              Oro Call Bundle
oro/crm-dotmailer                    4.1.6              Oro Dotmailer integration
oro/crm-hangouts-call-bundle         4.1.1              Oro Google Hangouts integration
oro/crm-magento-embedded-contact-us  4.1.2              OroCRM Magento Embedded Contact Us package
oro/crm-task-bundle                  4.1.5              Oro Task Bundle
oro/crm-zendesk                      4.1.4              OroCRM Zendesk Integration
oro/doctrine-extensions              1.2.2              Doctrine Extensions for MySQL and PostgreSQL.
oro/mailchimp                        4.1.5              Oro MailChimp integration
oro/marketing                        4.1.6              Oro Marketing Bundles
oro/oauth2-server                    4.1.7              Oro OAuth 2.0 authorization and resource server for BAP
oro/platform                         4.1.10             Business Application Platform (BAP)
oro/platform-serialised-fields       4.1.3              OroPlatform Serialized Fields
oro/redis-config                     4.1.5              OroRedisConfigBundle
oro/twig-inspector                   1.0.3              Oro Twig Inspector adds the possibility to find twig templates and blocks used for rend...
