### ISSUE TITLE
update Symfony Latest stable version: 6.1.4.

### ISSUE THREAD

**Issue by domaingood** [oroinc/platform#1088]
**Summary**  
update Symfony Latest stable version: 6.1.4.

**Comment by mbessolov** [comment]
Oro products release process is explained at https://doc.oroinc.com/community/release-process/
LTS version of Oro products are released using the latest LTS version of Symfony available at the time of the release.
The latest available LTS version of Symfony is 5.4.12 - https://symfony.com/releases
The next LTS version of Symfony will be 6.4, with the planned release date in November 2023 - https://symfony.com/releases/6.4
