### ISSUE TITLE
Localization bug in email templates

### ISSUE THREAD

**Issue by sbani** [oroinc/platform#320]
# EmailTemplate
## Problem

Step 1: Added Email Template with bug (`{% if entity.title not empty %}`) through data fixture
Step 2: Changed language from english to german.

If you try to change the email, you won't see the email and you won't be able to edit it.
Subject field and body field is empty. You can't switch to english version.
If you display the preview, it shows english version although german is changed.
If you save the german version the validation of english version throws error.

Emails won't be sent out.
## Solution
- Add english version to view without having to change the lanuage
- Show "default" email in any "new" language (here: show "english" mail to german users too)

Thank you all

**UPDATE 1:** First, the english email was sent with cron. After adding the german translation, the system sends the german mail. How to handle this? How to prevent unwanted behavior?

Code:

```
$emailTemplate = $this->entityManager->getRepository('OroEmailBundle:EmailTemplate')->findByName(
    self::TEMPLATE_THANK_YOU_NEW_LEAD
);

$templateData = $this->renderer->compileMessage(
    $emailTemplate,
    ['entity' => $lead]
);
```

**Comment by DimaSoroka** [comment]
Sorry, not sure i'm clear on what the issue is, based on description you may create a proper template with another fixture. Please provide more details on what you are trying to do and what doesn't work for you.

**Comment by sbani** [comment]
No problem.

I think, if you have an error in the email template, the error should only be thrown if you see the template and if you can edit it directly.

A user you wants to edit the english version don't want to see the error of the german version and he don't want to see the preview of the german version. He just wants to see the version he is currently working on.

The second point was more a question than a bug: Why is the system sending the german version of the template if I edit it and not the english one?

Do I overwrite the template if I change my language or do I add a "translation"?

**Comment by sbani** [comment]
Do you need any further information?

**Comment by artml** [comment]
@sbani let me check this bug in our backlog, it's been a while. The description looks clear to me though.

**Comment by sbani** [comment]
We are not using the product for quite a while now.
I'll close this issue.
