### ISSUE TITLE
Parameter id in audit route forces integer

### ISSUE THREAD

**Issue by sbani** [oroinc/platform#362]
My entity's  id is a `gid` and should stay like that.
Can I change the `oro_dataaudit_history` behavior? It looks wrong to me if you force `id` to be an integer.

The error:

```
An exception has been thrown during the rendering of a template ("Parameter "id" for route "oro_dataaudit_history" must match "\d+" ("fb22d8a9-9e7a-11e5-a0cc-525400d3eba4" given) to generate a corresponding URL.") in vendor/oro/platform/src/Oro/Bundle/DataAuditBundle/Resources/views/change_history_link.html.twig at line 6.
```

**Comment by alex-n-2k7** [comment]
Hi @sbani 
Actually we do not force 'id' to be an integer. In your own entity you are free to use any type you want. For now it's not clear what exactly behavior you  want to be changed.
Can you, please, describe your issue/usecase in more details ?

**Comment by sbani** [comment]
Hi @alex-n-2k7,

thank you for your fast reply! I don't have that issue today after some cache:clear and platform:update.
I thought it's a sub request which expects the `id` to be an integer.

But I was obviously wrong.

**Comment by sbani** [comment]
Issue occures again.

In the [AuditController](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/DataAuditBundle/Controller/AuditController.php#L35)
```php
     * @Route(
     *      "/history/{entity}/{id}/{_format}",
     *      name="oro_dataaudit_history",
     *      requirements={"entity"="[a-zA-Z0-9_]+", "id"="\d+"},
     *      defaults={"entity"="entity", "id"=0, "_format" = "html"}
     * )
```

The id of my own entity is not an integer. THat's what's causing the problem

**Comment by alex-n-2k7** [comment]
Hi @sbani,
I think we can remove the requirement for the identifier ("id"="\d+"), 
but can you, please, recheck it too and confirm that everything else related to data audit functionality works fine ( changes logging and display ) ?

We'll also check it tomorrow.
So, the annotation will looks like this:
```
/**
 * @Route(
 *      "/history/{entity}/{id}/{_format}",
 *      name="oro_dataaudit_history",
 *      requirements={"entity"="[a-zA-Z0-9_]+"},
 *      defaults={"_format" = "html"}
 * )
 * @Template("OroDataAuditBundle:Audit/widget:history.html.twig")
...
```

Please note that it will require some changes in API side, so the full fix can take some more time, but if you're interested only in UI ( history grid per certain entity ) the above solution should be enough.

**Comment by mbessolov** [comment]
_Internal reference - BAP-9706_

**Comment by sbani** [comment]
We are not using the product for quite a while now.
I'll close this issue.
