### ISSUE TITLE
Problem with country of Contacts

### ISSUE THREAD

**Issue by chatlovely** [oroinc/platform#381]
I am using oro crm 1.8.2 that is latest version Now . i installed that on 2 domain and when i add a contact with a country such as Germany or other thing the map don't show any thing and said Sorry Location is unavailable but in orocrm demo is that right working ! in my installation just can add American Address. can you help me , that is bug for other users ?

**Comment by artml** [comment]
Hi,

Can you please share a screenshot or provide the address you have trouble with so we can check it? Thank you

**Comment by chatlovely** [comment]
Thanks for answer to me , when an address not have a google map address in system then that remain in loading mode , maybe it show 1 time correctly but it on second time have remain in loading mode, for link , can i have your email and send link& user password to your email for check ?
![screeen](https://cloud.githubusercontent.com/assets/10954208/12379770/a015854a-bd58-11e5-8bbf-93d5d1de1643.png)

**Comment by chatlovely** [comment]
I founded problem and got solution for that , but this bug must be solve for future version
When primary location in configuration page is set on other country (No USA) then i have problem but after i set it on usa then my problem was solved .

**Comment by artml** [comment]
Thank you for the heads up, we will fix it in the upcoming versions.

**Comment by sadortun** [comment]
@artml Any news on this ? Issue is still in `master`

**Comment by artml** [comment]
@sadortun tested it at our current dev master with Ukrainian address and the map works perfectly (pic related). Which country doesn't work for you?

![address](https://cloud.githubusercontent.com/assets/4727902/16453900/32176d0c-3e17-11e6-8800-c3766306aa25.png)

**Comment by sadortun** [comment]
In Canada

**Comment by artml** [comment]
Canada is fine too. I even tried omitting the province in the address, but it still points to the correct location.

![bmo field](https://cloud.githubusercontent.com/assets/4727902/16454335/fe392d0c-3e18-11e6-809b-c655c06a429b.png)

¯\_(ツ)_/¯

What are your STR? I just create a contact with an address, that's it. The build is yesterday's master.

**Comment by sadortun** [comment]
This was release not long ago by Google.

> Standard Plan Updates
> 
> Google Maps APIs Standard Plan updates implemented on June 22, 2016, are as follows:
> 
> **We no longer support keyless access (any request that doesn't include an API key). Future product updates are only available for requests made with an API key.**
> 
> We have implemented a simple 25,000 map loads per day free limit for new Google Maps JavaScript API, Static Maps API, and Street View Image API implementations. The rolling 90-day grace period for existing applications is being retired on October 12, 2016.
> 
> We have reduced the maximum daily map load limit you can purchase for Google Maps JavaScript API, Static Maps API, and Street View Image API from 1,000,000 to 100,000 requests. Developers requiring higher quota should contact Sales to discuss a Premium Plan license.

>  We now count Google Maps JavaScript API client-side service requests towards the daily limit of the associated web service API.
https://developers.google.com/maps/pricing-and-plans/standard-plan-2016-update

**Comment by sadortun** [comment]
FYI 2 :

**On the Oro Demo,** Google Maps diplay the following warning in the console
![image](https://cloud.githubusercontent.com/assets/794449/16456162/f7c9f9a8-3de4-11e6-8f1d-353e9eba0685.png)


Versus on **my installation** : 
![image](https://cloud.githubusercontent.com/assets/794449/16456188/13380770-3de5-11e6-86f7-5100a9845435.png)

**Comment by artml** [comment]
@sadortun apparently these API changes are rolled out gradually and some of our servers are already affected while others are not. We'll investigate it so the appropriate changes are included into 1.10 release.

Thanks for the info!

**Comment by aivus** [comment]
JFI, ticket internal ID: BAP-13434

**Comment by aivus** [comment]
This issue was fixed in master and will be shipped in 2.4

**Comment by sadortun** [comment]
@aivus didnyojimplement the fox on the 2.3 LTS?

**Comment by aivus** [comment]
@sadortun no, this fix was shipped only to 2.4.

**Comment by sadortun** [comment]
@aivus Can you point me to the commit?  ill chery-pick it and submit a PR if you want.

Thanks

**Comment by aivus** [comment]
@sadortun 
https://github.com/oroinc/platform/commit/16da5cb54a60bae14d982ea53826d1117221636d
https://github.com/oroinc/customer-portal/commit/e6cf77397f65e46797ffd53e07e2c3441574b07b
