### ISSUE TITLE
Feature Request : Add/Edit  Select and Multi-Select fields

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#478]
Hi ORO Team,

The current enum field editor is very pretry, and works nice if you only have a few values, but in the case of many values 20+ you need to enter them by hand, which is very long and painfull.

Would it be possible to add a simple textbox with `one value per line` 

Thanks,
Samuel

**Comment by artml** [comment]
@sadortun we allow to import entity fields via CSV, maybe it will help relieve the pain?

I'm afraid that one value per line textboox won't allow for advanced enum capabilities, such as choosing a default value, or working with "system" values that cannot be deleted. (We don't have these yet, but will have them in 1.10 release—some lead and opportunity statuses won't be removable.)

**Comment by sadortun** [comment]
Hi @artml I totally understand the implication. Maybe the `quick edit` mode should not be available for system entities. For the selection of default, i think it still dooable. In my opinion, the textarea view should only be to add or modify bulk values, the current view would be still the main view.

If you have already tried to populate many values, you will notice that it very impratical to do so currently. For example, if you add a "State" enum with the 50 states in the US, with the current UI, you need to expand to have 50 rows, then copy/paste every values in each fields ....

**Comment by artml** [comment]
I see the value in this idea, but it won't be high on our priority list for the next release or two.

**Comment by mkudelya** [comment]
Hi @sadortun 

Enum values is a regular table. Small script which translate from text lines to sql will help you.
I think as a workaround, it would be useful.

**Comment by sadortun** [comment]
Yes, this is already what we did, but juts still an issue because this is a task a regular user need to be able to do ! 

Also, when values contains special char, they need to be escaped for the enum key...

**Comment by mkudelya** [comment]
Hi @sadortun 

We will consider all your wishes, thank you for the suggestions!
