### ISSUE TITLE
[WIP] Extend entities improvements

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#479]
Hi Oro Team,

We would like to improve the Extend Entities bundles to improve it ease of use and make it more efficient for RAD. We would appreciate your feedback on this topic in order to decide if a PR could be merged back, or if we should submit an extension. Feel free to email me, or we could schedule a call.

We have a couple of basic requirements that would help to make more use of the Extended entities. Maybe theses are somewhat currently  covered, but we could not find docs.

The following requirement use the following definitions :
- **The Manager**  :  Person who can make change to the Entity Management modules through the web interface 
- **The Developer** : Person who make change in code / templates.

Proposed requirements :
- [ ] The Developer shall be able to manipulate Extended entities as if they would be regular Doctrine entities. That mean, being able to create them, modify them, and delete them.
- [ ] The Developer shall be able to create a relation between  a regular entity and an Extended entity.
- [ ] The Manager shall have a visual aid to see which fields are currently locked.
- [ ] To prevent the Manager to break things, (which would be **very bad,** ), The developer shall be able to use a  configuration/annotation to **lock**  Extended entities, or specific fields in theses entities

**Comment by DimaSoroka** [comment]
hi @sadortun 

Requirements you described are currently supported:
- Developer can introduce new entity types and work with extended entities as with regular doctrine entities
- Relations are supported and could be defined by developer
- On entity level you can define system fields (locked) and extended ones (could be updated by manager)
- Manager could delete only custom entities, if extended entity introduced via bundle manager can't delete it as well as can't delete extended fields

Take a look into Contact, Account or User entities - they are extended entities (so manager can manage extended fields) and they have system fields.

**Comment by sadortun** [comment]
Hello @DimaSoroka,

Thanks for your quick update!  I've already noticed that your points are already supported. The current workflow require the developer to create the entities first in a bundle. The goal of the addition would be to be able for the manager to create the new entities. And then, later on, if needed to have the developer add new functionalities to the pre-existing entities created by the manager.

Have a good day,
Samuel

**Comment by DimaSoroka** [comment]
If i understood you correctly, you are looking for Manager to define initial data structure first and then Developer to be able to use it as a starting point. I think this will be very valuable addition. 
We will be happy to participate in the solution architecture design and review.

**Comment by sadortun** [comment]
Exact ! We are happy to see you are interested in the idea!

**Comment by sadortun** [comment]
Hi again @DimaSoroka please send me en email to see how we can coordonate to implement this.  We need something working around July 20, we should have the architecture and design ready somewhere around the end of next week.
