### ISSUE TITLE
[BUG] ID is limited to integer (again) - Workflow*

### ISSUE THREAD

**Issue by sbani** [oroinc/platform#505]
Hi,

same issue like in #362.
Please do not force the user to use integer ids.

Broken code: `"workflowItemId"="\d+"`
WorkflowBundle/Controller/Api/Rest/WorkflowController.php

``` php
    /**
     * @Rest\Get(
     *      "/api/rest/{version}/workflow/transit/{workflowItemId}/{transitionName}",
     *      requirements={"version"="latest|v1", "workflowItemId"="\d+"},
     *      defaults={"version"="latest", "_format"="json"}
     * )
```

Plus the entity_id in `WorkflowItem`:

``` php
    /**
     * @var int
     *
     * @ORM\Column(name="entity_id", type="integer", nullable=true)
     * @Serializer\Expose()
     */
    protected $entityId;
```

**Comment by mkudelya** [comment]
@sbani I'm wondering, why do you not want to just delete this constraint in your customization? I think is not hard. Our platform is working with integer primary keys and i don't know how these changes will affect performance.

**Comment by sbani** [comment]
@mkudelya: **If the user has to use integer ids for each entity, then please say so in the docs**. If everybody always has to add a second column called "token" because of your forced integer ids, people have to know.

You are right, that it's not that hard to add a second column. But the token column is not needed in many cases because doctrine can handle uuid as identifier and symfony has no problems with it either.

**Comment by sbani** [comment]
We are not using the product for quite a while now.
I'll close this issue.
