### ISSUE TITLE
Bundled moment.js is out of date

### ISSUE THREAD

**Issue by adamlundrigan** [oroinc/platform#530]
The LocaleBundle bundles a version of moment.js which is out of date:

https://github.com/orocrm/platform/blob/c9c0fd8219719d6883c1981e9f3b2c7a02e151d1/src/Oro/Bundle/LocaleBundle/Resources/public/lib/moment/moment.js

Is there a specific reason for pinning to this version?  The platform pulls moment.js 2.15.0 through Composer but LocaleBundle doesn't make use of that copy.

**Comment by Grygir** [comment]
Hi,

We've used own copy of moment version 2.8.3, that contains hot fix for issue https://github.com/moment/moment/issues/2186
But it looks like in newer version the issue is already fixed https://github.com/moment/moment/pull/3078

We need to check if we are ready to use last version moment.

Thank you for your question.

**Comment by sergeyz** [comment]
@Grygir https://github.com/moment/moment/blob/develop/composer.json#L2 we can add it using component now

**Comment by Grygir** [comment]
@sergeyz sure, we just need to check if new version does not break any other functionality that we have

**Comment by artml** [comment]
@Grygir have we checked it?

**Comment by Grygir** [comment]
@artml not yet, but we have it in plans

**Comment by Grygir** [comment]
Moment.JS of version 2.15.2 still has issue moment/moment#2186, so we can not use it without hotfix.

**Comment by mkudelya** [comment]
Hi @Grygir 

Could you tell me, now we can update the library ?

<img width="472" alt="screen shot 2017-03-10 at 17 49 50" src="https://cloud.githubusercontent.com/assets/3332593/23801827/284f16c4-05ba-11e7-8c31-f36ce1f4df8a.png">

**Comment by Grygir** [comment]
No, we can not. The issue still exists in latest version of moment. See validation result for months with period in name:
https://jsfiddle.net/99sejg9j/2/

**Comment by mkudelya** [comment]
Is there a chance to upgrade? [2.10](https://github.com/moment/moment/issues/2186#issuecomment-74717157) has already been released, could you please again remind the author about this error?

**Comment by Grygir** [comment]
I did, several times. Looks like it is not a prior issues for the author.
You can remind author about it by yourself, it might increase priority for the issue.

**Comment by mkudelya** [comment]
Waiting for an answer
https://github.com/moment/moment/issues/3856

**Comment by mkudelya** [comment]
@Grygir 
Good news. Bug has been fixed.
https://github.com/moment/moment/issues/3856#issuecomment-288285970

**Comment by Grygir** [comment]
@mkudelya that's great! We will plan the library upgrade.

**Comment by vbyndych** [comment]
The library was successfully updated. So I'm now closing this issue.
