### ISSUE TITLE
Refactor oro:platform:update

### ISSUE THREAD

**Issue by sbani** [oroinc/platform#534]
@DimaSoroka wanted me to explain the pain with the command `oro:platform:update` and I explained it in slack. Because of no answer, I create this issue with the same text from slack.
# About the `oro:platform:update` process.
## Problem

If you use a cloud hoster (container) or a hoster like platform.sh (specialized for symfony projects) or a CI build process, you need (and want) a two-part update process. This is supposed to become the default process with the rise of containers - it is already for most nodejs projects and various of compiled languages (like Go).
1. Step: build
   You build the project on your CI or any other system first. Build means that you prepare all files like assets, or the file/folder structure itself. You have write access "everywhere".
   But you don't have database access in this step because this can be done on any server.
   The command `cache:warmup` reflects that for symfony.
2. Step: update
   After you prepared your package, the files will be "uploaded" to the prod endpoint. At this point you have database access to the prod db, BUT folder management changed completely.
   In this environment you normally want to write to "shared" folders only. 
   Example: uploads, cache, sessions
   The rest of the system can be - or should be - read only. This is not mandatory for containers, but makes sense, because you have no need to write to other folders and the source of your projects never changes.

The problem with oro is, that there are too many commands in `oro:platform:update` that need database access. From anther point of view: Some commands want to write to folders like `web` (non-shared-folders) after database usage 
This is bad practice.
## Solution

There is a good and simple way to go:
1. Split database and non-database commands
2. Run non-database commands first
3. Try to remove database usage from as many commands as possible.

I know that you use a lot of database in platform update, but there are many commands which don't need or better shouldn't use database at all. Example: translations.
## Side notes

All these points will get more and more attention as soon as there are more "cloud"/container users who use a "two-step deployment" in the php ecosystem.
You find a lot of examples outside the php ecosystem. Within the php community eZpublish and Drupal seem to publish examples.

**Comment by DimaSoroka** [comment]
Thanks @sbani!

We already facing this issue and working on the solution. In other words file system cache  warmup/build operations should be based ONLY on source code of the application and data cache warmup/deploy operations could use database. Key challenge for now is around extended entities, we are thinking how to solve it in best way.

**Comment by sbani** [comment]
While there are more and more people facing the issue, I will come up with the big questions here:

**Do you have any concrete plans?** 
Your comment sounds like you are already working on it.
**Do we see any changes in platform 2.0?**
**Do you plan to change the oro workflow step by step or is it more a complete refactoring?**

For me, many features are cool but are implemented "old fashioned" or "unpractical". Most of the "code" is placed in the database which makes the database mandatory for each step (as we can see). This behavior is not recommended. Perhaps, you should better place this generated code on the filesystem.

Entity extend is very special and unhandy in general, I understand that. But why not generating files from user input? Plain old PHP files. Because that is somehow already happening on `cache:clear`. Advanced users can create generated files and commit, edit, publish them and do not need database on `warmup` anymore. All other users don't even know the difference. Needless to say, that users need to know about the file changes and that a (server) migration needs to be done with files too. (And yep, I know that's the unhandy point here).

We can ague about that all day long, but at the moment and with the current procedure, the platform is making life difficult for itself.

What do you think?

**Comment by DimaSoroka** [comment]
hi guys

Here is what we are doing and planning to do in regard of this issue as it has direct impact on establishment and configuration of CI/CD for Oro applications. 

# Build
As part of the build process we run all tests (unit, functional, Behat and Selenium) and on successful tests execution we prepare artifact with application source code (all dependencies, assets and file caches) and application DB dump. To prepare artifacts we simply install application and take snapshots of file system and DB right after. Artifacts structure depends on your environment and deployment process, it could be an archive or could be a docker container or anything else.

# Deploy and Run
Deployment process is based on artifacts generated as result of build and provisioning DB from dump with replacement of DB credentials in parameters and application cache. Once it is done you can limit permissions to cache folder, but... this will require to limit access to entities manager. This is known issue and we plan to fix it next year.

# Upgrade 
Upgrade is big area for improvements. The first step we made with 1.12 release, and continue improving on it, is backward and forward compatibility of the database within minor version of the application. This  allows to run different patch versions of the application on the same DB and use rolling upgrades for the new version. As part of this process you currently need to execute `oro:platform:update` and this could be done by deployment process with more advance permissions. For minor version upgrade application should be switched to maintenance mode and requires downtime. 

# Questions
To address questions above:

1. Do you have any concrete plans? 
Yes, we do have the following plan:
  a. Enable schema less custom fields management that will not require entity proxy regeneration
  b. Disable any other runtime changes in application cache folder
  b. Enable schema backward compatibility support between minor releases
2. Do we see any changes in platform 2.0?
Unfortunately not yet
3. Do you plan to change things step by step or will it be more of a complete refactoring?
For some items it will be complete refactoring, and some will be enabled step by step. 

I hope this information will help you to understand our plans and vision, we will be happy to collaborate on any item that could help to make application build and deployment more smooth and stable.

**Comment by sbani** [comment]
Thank you @DimaSoroka for the long and thoughtful comment and the fast response. It helps a lot to understand the process.

Let me comment some minor points with my ideas:
> To prepare artifacts we simply install application and take snapshots of file system and DB right after.
That's what we also do and which "works fine" on our CI system. But please think about the case that you have a hotfix (without database changes). In this scenario, you have to know what you are doing, but if you do (think about an error in frontend code) you'll want the deployment to be as fast as possible. In this case: assets, cache:warmup. You should always be able to prepare code only to create the package.
At the moment we have to run the installation process on the CI, which costs us ~4min.

> Once it is done you can limit permissions to cache folder, but... 
The problem is that there are some systems out there where the permissions are already limited when "build" is done. That's nothing we can change. Though, that's a point we can discuss to support.
But nevertheless, supporting the use case of a complete build without database is a good thing to achieve.

**Comment by sergeyz** [comment]
@sbani Hi, I'm going to fix the issue with database connection for assets command. Next commands works for me without DB connection.

```
            php app/console oro:localization:dump --env test;
            php app/console oro:assets:install --env test;
            php app/console assetic:dump --env test;
            php app/console oro:requirejs:build --env test;
```

The main issue - warmed caches should not be used after assets build without a database. In most cases they are wrong.

**Comment by nesl247** [comment]
Any update on this?

**Comment by anyt** [comment]
> The main issue - warmed caches should not be used after assets build without a database. In most cases they are wrong.

The only module that connects to the database during assets build is the Doctrine library. It's done during the build of the Symfony container to know what database server version you are using as the container configuration provided by Doctrine depends on it. 

You can prevent connection to the database by specifying the server_version manually in a `config_prod.yml` file, but don't forget to change it after the database server version update on a production server.
See [Doctrine Configuration Reference](https://symfony.com/doc/3.4/reference/configuration/doctrine.html#doctrine-dbal-configuration).

**Comment by sbani** [comment]
We are not using the product for quite a while now.
I'll close this issue.
