### ISSUE TITLE
Migration to 2.x

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#617]
Hi Oro Team,

We are migrating a few applications to `2.x`, and i think there is a few errors other users might fell into. I've documented them, if it can help anyone! 

PS : The list might get longer, i've grouped all the foundings here instead of creating a ton of different issues.

## Migrations
- [ ] When a migration fail in the SQL,  re-running the migration, the sql queries are executed when re-running the failed migration, but it seems like the `oro_entity_config` are not updated.  **I have to say that this has been a serious pain !!** :nauseated_face:  When an error occured during a migration, we needed to take note of what went wrong,  restore the database,  fix all the errors that occured manually, and re-run. Again, and again ...
- [ ] When introducing new `PRIMARY` or `UNIQUE` keys, it might worth testing before for duplicate in order to exit gracefully and avoid the problem mentioned above

Duplicates were in `oro_audit` and `oro_translation`, finding and removing the duplicates first, to help the migrations : 
```sql
SELECT * FROM `oro_audit` group by object_id, object_class,version having count(*) > 1
SELECT * FROM `oro_translation` group by `key`,`domain` having count(*) > 1 ORDER BY `oro_translation`.`key` ASC 
```

## TagBundle
- [ ] It seems there is a migration missing to rename all the oro_tagging  entities from  `OroCRM\.....` to `Oro\....` This cause all tagging pages to stop working.
```sql
UPDATE oro_tag_tagging SET entity_name=REPLACE(entity_name,'OroCRM','Oro') 
```
   - [ ] Also, it might worth adding checks in `TagBundle` to ensure the target entity exists, there is a few exceptions throwing here and there

## UI
- [ ] The pin bar labels are not updated from `orocrm_....` to `oro_.....`
![image](https://cloud.githubusercontent.com/assets/794449/22180569/a79213da-e041-11e6-9ec6-297bfb7b1a0f.png)

- [ ] Notice ....
![image](https://cloud.githubusercontent.com/assets/794449/22181472/6979ddc0-e05b-11e6-90ad-9de9d1a38ab8.png)

Seems like the labels are updated when clicking on the links

## Tracking Bundle
- [ ] `Oro\Bundle\TrackingBundle\Migrations\Schema\v1_11\InstallTrackingScriptQuery` do copy the `tracking.php` correctly, but it's a bad idea to do this in a migration. This migration will not run again, and it will not work in new installations that already have the migration executed ( aka CD) 

## Cron / Message Queue bundle
- [ ] It seems there is no way to view the output of a cron command.  That was very usefull to know what is going on ... Any plans to re-enable this ? 

## Lexik Lock

In your upgrade guide, you mentioned to lock
`$ sudo -uwww-data app/console lexik:maintenance:lock --env prod`

Then ` sudo rm -rf app/cache/*`

But, as per the configuration, the lock file is in `app/cache/` :face_with_head_bandage: 
```yaml
lexik_maintenance:
    driver:
        class:                Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver
        options:
            file_path:        %kernel.root_dir%/cache/maintenance_lock
```

hehe

Thanks,
Samuel

**Comment by mkudelya** [comment]
> When a migration fail in the SQL, re-running the migration, the sql queries are executed when re-running the failed migration, but it seems like the oro_entity_config are not updated. I have to say that this has been a serious pain !! :nauseated_face: When an error occured during a migration, we needed to take note of what went wrong, restore the database, fix all the errors that occured manually, and re-run. Again, and again ...

Can you provide any STR to reproduce ? Which migration did fail? What is wrong with oro_entity_config? How did you fix this table?

> When introducing new PRIMARY or UNIQUE keys, it might worth testing before for duplicate in order to exit gracefully and avoid the problem mentioned above

This will be fixed in the next release. Thanks!

> It seems there is a migration missing to rename all the oro_tagging entities from OroCRM\..... to Oro\.... This cause all tagging pages to stop working.

Yes, i will create ticket for the bug.

**Comment by mkudelya** [comment]
> The pin bar labels are not updated from orocrm_.... to oro_.....

> Notice .... Seems like the labels are updated when clicking on the links

I'm currently on 2.0 branch and don't these issues, perhaps they were fixed.

> Oro\Bundle\TrackingBundle\Migrations\Schema\v1_11\InstallTrackingScriptQuery do copy the tracking.php correctly, but it's a bad idea to do this in a migration. This migration will not run again, and it will not work in new installations that already have the migration executed ( aka CD)

I do not fully understand why this is a bad idea. Why does the file copy again? In new installation system will [copy](https://github.com/laboro/dev/blob/master/package/marketing/src/Oro/Bundle/TrackingBundle/Migrations/Schema/OroTrackingBundleInstaller.php#L38-L40) the file.

> It seems there is no way to view the output of a cron command. That was very usefull to know what is going on ... Any plans to re-enable this ?

I will add improvement. Thanks.

**Comment by sadortun** [comment]
> Can you provide any STR to reproduce ? Which migration did fail? What is wrong with oro_entity_config? How did you fix this table?
One of the first issue I had was an exception  `Contact:: $picture` Entity was not found. After this, one of the migration SQL statements were executed,  but not the entity_configs changes. 

I had to revert a backup and start over.

> I do not fully understand why this is a bad idea. Why does the file copy again? In new installation system will copy the file.
```
App/console oro:platform:update  # tracker.php copied
git clean -f -d
Gît pull
App/console oro:platform:update  # tracker.php will not be copied since migration is already executed.
```

**Comment by mkudelya** [comment]
> It seems there is no way to view the output of a cron command. That was very usefull to know what is going on ... Any plans to re-enable this ?

At the moment you can see output in the logs. Or do you mean a different location? If yes, please indicate where (for example screenshot)

> In your upgrade guide, you mentioned to lock
$ sudo -uwww-data app/console lexik:maintenance:lock --env prod
Then sudo rm -rf app/cache/*
But, as per the configuration, the lock file is in app/cache/

Yes, it is contradictory actions.

**Comment by sadortun** [comment]
> At the moment you can see output in the logs. Or do you mean a different location? If yes, please indicate where (for example screenshot)

In 1.x, you could view the output of the commands by clicking on them in the job Queue. 

As you mentioned, we can redirect the output of the message queue run command to a log file,  but itsince a nice to be able to look it up from the UI directly.

**Comment by mkudelya** [comment]
> This should work :
App/console oro:platform:update  # tracker.php copied
git clean -f -d
Gît pull
App/console oro:platform:update  # tracker.php will not be copied since migration is already executed.

I have tried run 'git clean -f -d', command deleted all untracked files except web/tracker.php
Do you have tracker.php in [.gitignore](https://github.com/orocrm/crm-application/blob/2.0/.gitignore#L21) ?

**Comment by sadortun** [comment]
No. The idea is that the file should be copied again on 'oro:platform:update' to ensure the file is present.

**Comment by mkudelya** [comment]
> In 1.x, you could view the output of the commands by clicking on them in the job Queue.

improvement has been created

**Comment by mkudelya** [comment]
> In your upgrade guide, you mentioned to lock
$ sudo -uwww-data app/console lexik:maintenance:lock --env prod
Then sudo rm -rf app/cache/*
But, as per the configuration, the lock file is in app/cache/

also created.

**Comment by mkudelya** [comment]
>No. The idea is that the file should be copied again on 'oro:platform:update' to ensure the file is present.

For now this is done via migration, i think the fastest way to resolve this issue by passing this file to .gitignore. Why not?

**Comment by sadortun** [comment]
I don't think this is going to help for CD. 

For now I simply added the `cp` in composer `postInstall` and `postUpdate` scripts

**Comment by sadortun** [comment]
Old issue, no more relevant since we are at version 3.x.
