### ISSUE TITLE
Orphaned definition of "oro_user.form.role" in Oro/Bundle/UserBundle

### ISSUE THREAD

**Issue by cawolf** [oroinc/platform#632]
Hey,

we are currently upgrading to 1.10 and our smoke test found a misconfiguration in the `Oro/Bundle/UserBundle/Resources/config/form.yml`:

    oro_user.form.role:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["oro_user_role_form", "oro_user_role"]

The definition of `oro_user_role` was obviously removed, but this definition still refers to it. It would be great if you could fix this issue in an upcoming release. Thanks in advance,

best regards,
Christian

**Comment by mkudelya** [comment]
Hi @cawolf 

Improvement has been created and will be fixed as soon as possible.
Thank you
