### ISSUE TITLE
Symfony debugbar problem 

### ISSUE THREAD

**Issue by jneto81** [oroinc/platform#640]
In version 2 , the  debugbar data don't update on Ajax navigation

**Comment by mkudelya** [comment]
Hi @jneto81,

Thanks for reporting the issue! We will do our best to fix it as soon as possible!

**Comment by jneto81** [comment]
Any news about this ?

**Comment by jneto81** [comment]
I'm closing this issue because it seems fixed with ORO 3.1.9.
