### ISSUE TITLE
NumberFormatter options "decimalSeparator" and "orderSeparator" are ignored

### ISSUE THREAD

**Issue by cawolf** [oroinc/platform#647]
Hi,

since 1.10, we are experiencing a nusiance while displaying integers in NumberFilters: they are always shown in groups separated by a default `orderSeparator`. Trying to overwrite this formatter option doesn't work, and I think the reason are the 3 added lines in the [number-formatter.js](https://github.com/orocrm/platform/blob/776b6045830977acb8a81c7453cb3bc02d47fa73/src/Oro/Bundle/FilterBundle/Resources/public/js/formatter/number-formatter.js#L28-L30), which reset any given parameter for both `decimalSeparator` and `orderSeparator` to the language default. 

Perhaps moving those lines before the `_.extend` call could fix this issue.

Best regards,
@cawolf

**Comment by mkudelya** [comment]
Hi @cawolf 

Thank you for reporting the issue! We greatly appreciate all contributions to Oro projects. We will do our best to fix the issue as soon as possible!
