### ISSUE TITLE
[API Bundle] - using other than primary key identifier field for doctrine entity

### ISSUE THREAD

**Issue by mechpave** [oroinc/platform#653]
Hi,
I have a question regarding identifier fields for entities to be used by API Bundle (new JSON API).
In our project, we have two id fields for entity:
- id - integer - auto increment, primary key. We use it for primary and foreign keys in other tables.
- uuid - guid. We want to use this field to access entity via external API

The problem is that generated GET endpoint looks like this: `http://project.dev/api/entity/{id}`, and we would like it to be `http://project.dev/api/entity/{uuid}`. In other words, we do not want to use the `id` field for outside requests between our server and mobile apps.
I have tried to change it in `api.yml` config type by setting `identifier_field_names` to `[uuid]`, but it seems that identifier field is retrieved from Doctrine entity metadata and is not overwritten by `identifier_field_names`.

Is it possible to change this behavior? If not, I would appreciate any hints about internal ORO code that handles this situation.

**Comment by vsoroka** [comment]
Hello @mechpave ,

Unfortunately for now there is no easy way to achieve the requested behavior. I've added this task in our backlog, but for now I cannot say when it will be implemented. You are welcome to contribute this improvement as well.

**Comment by mechpave** [comment]
@vsoroka, thank you for quick response.
I would gladly contribute to implement this feature, but I am not quite familiar with internals of API bundle yet. Could you give me any hints about the classes that handle identifier fields and generate endpoints?
It would be easier for me to develop this feature then.
Thanks

**Comment by vsoroka** [comment]
I will try to investigate this in the nearest few days and provide the hints.

**Comment by mechpave** [comment]
@vsoroka, as I understand, `identifier_field_names` configuration is being used only for other than ORM entities. For now, my plan is to get identifier fields from entity metadata only if this field is not present. How does it sound?

**Comment by vsoroka** [comment]
@mechpave You are right, for now this configuration works only for not ORM entities. Your plan sounds good.

**Comment by vsoroka** [comment]
Fixed, starting from version 2.5 the `identifier_field_names` works for ORM entities as well.
Here is details: [Using a non-primary key to identify entity](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/ApiBundle/Resources/doc/how_to.md#using-a-non-primary-key-to-identify-entity)
