### ISSUE TITLE
[API Bundle] - CountQuery do not resolve query hints

### ISSUE THREAD

**Issue by geoffroycochard** [oroinc/platform#658]
Hie,
I'm using a query hint to filter datas.
The hint work perfectly when retrieving datas via EnititySerializer and `Oro\Component\EntitySerializer\QueryFactory` but when i request `totalCount' the query hint push in context configuration is not resolving by `SetTotalCountHeader->calculateTotalCount()`.

I'm tested to resolve hint in `oro_api.get_list.set_total_count_header` service before call [`QueryCountCalculator::calculateCount($countQuery)`](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ApiBundle/Processor/Shared/SetTotalCountHeader.php#L138) via `$this->queryHintResolver->resolveHints($countQuery, $context->getConfig()->getHints());`, and it's Ok.

It's perhaps due behavior do not resolve query hint for `oro_api.get_list.set_total_count_header` service ?

To do not modify CORE, i'm going to try to create a service executed before `oro_api.get_list.set_total_count_header` service and assign total count header.

**Comment by geoffroycochard** [comment]
> To do not modify CORE, i'm going to try to create a service executed before oro_api.get_list.set_total_count_header service and assign total count header.

It's working

**Comment by vsoroka** [comment]
Hi @geoffroycochard ,

> It's perhaps due behavior do not resolve query hint for `oro_api.get_list.set_total_count_header` service ?

It is a bug. To fix it we need to inject `oro_entity.query_hint_resolver` service in `oro_api.get_list.set_total_count_header` and call `QueryHintResolver::resolveHints` in `SetTotalCountHeader::calculateTotalCount`.

Do you have a chance to contribute this fix? If no, I'll create the task for our team.

**Comment by vsoroka** [comment]
INTERNAL ID: BAP-16352

**Comment by vsoroka** [comment]
The fix will be available since version 2.6.
