### ISSUE TITLE
Navigation in activity log: "older" is falsely enabled

### ISSUE THREAD

**Issue by cawolf** [oroinc/platform#663]
Hi there,

I stumbled upon a smaller bug in the activity log navigation. The buttons "newer" and "older" usually work correctly, but if you have exactly 10 (or a multiple of 10) entries in the log, the "older" button on the last page suddenly is enabled and clickable, resulting in the same 10 entries being loaded again. 

I can reproduce this in your open demo, but a backport of the fix for this in the v1.10 branch would help us a lot. Thanks in advance,

best regards,
@cawolf

**Comment by mkudelya** [comment]
Hi @cawolf 

Thank you for reporting the issue!
We greatly appreciate all contributions to Oro projects.
