### ISSUE TITLE
ReplaceNamespaces Migration fail

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#664]
Hi Oro Team,

During the ReplaceNamespaces migration on 2.x, if the target audit field version already exists, the migration will stop and fail with an exception. There is proabaly a `try{} catch{}` missing in platform/src/Oro/Bundle/InstallerBundle/Migration/UpdateTableFieldQuery.php:98

Looking at the migration, the replacement is done via PHP code, instead of a single SQL query which would be more efficient.

If someone else have a similar issue, you can run the following queries on the oro_audit table to avoid duplicates:
```sql
update ignore `oro_audit` SET object_class=REPLACE(object_class,'OroCRM','Oro');
delete from oro_audit WHERE `object_class` LIKE 'OroCRM%';
```

Thanks
Samuel

**Comment by inri13666** [comment]
Hi Samuel,
Thank you for reporting the issue.

Unfortunately, your suggested SQL query makes updates for only non-conflicted audit records and leaves all conflicted records with old namespaces. 
For now, the query _can not_ be a recommended solution for the issue as on conflict cases an audit data should be properly merged.

We will try to fix it as soon as possible.

Best Regards,
Nikita Makarov

**Comment by anyt** [comment]
Already fixed.

Thank you for contribution!
