### ISSUE TITLE
Knowing which users are currently online?

### ISSUE THREAD

**Issue by VinnyVicious** [oroinc/platform#670]
Is there a way of knowing which users are currently online in the platform? Maybe a table that tracks sessions or something?

**Comment by RocKordier** [comment]
Hey @VinnyVicious 
i think you should use a Symfony service for that:
`$this->get('security.token_storage')->getToken()->getUser();`

Hope that helps,
Eric

**Comment by manowark** [comment]
@VinnyVicious, as I understand you need some realtime tracking, that should notify application every (for example) 5 second about user activity. If yes - now we don't have such functionality.

We greatly appreciate all contributions to Oro projects.
