### ISSUE TITLE
Bug: "running" jobs that are non existent prevent other jobs to be scheduled

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#674]
HI Oro team,

We have noticed on an installation that the `cron imap` sync job were not scheduled since March 22. ( 15 days ago). The job probably got killed when doing some maintenance and did not complete. 

It seems that since the job wereasier never garbage collected, and that since it was still listed as incomplete, it was not scheduled again by the task scheduler. 

Is there a GCE mechanism to prevent jobs that no longer exists (either killed by the OS, crashed or that is stuck) ?
![20170408_215437](https://cloud.githubusercontent.com/assets/794449/24833951/0e7a7be6-1ca6-11e7-86d6-f0d9794990f6.png)
![20170408_215418](https://cloud.githubusercontent.com/assets/794449/24833952/148eee36-1ca6-11e7-9284-e2ea60813a92.png)

As you can see, usually the command takes about 1sec to run. And run last 15 days ago.
Deleting the job from queue, and from jobs_unique allowed the job to be rescheduled normally.

Have a good day,
Samuel

**Comment by manowark** [comment]
Hi, @sadortun.

Thank you for reporting this issue. We will fix it in short time.

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/platform/commit/42a45d70b980359f086868c64350c5448515c53d.

Thank you for contribution!
