### ISSUE TITLE
2.1 Unhandle exception in message queue caise it to stop processing 

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#679]
HI,  

When an exception is thrown in the message queue, it stop to process any messages and exit. 

![screenshot_20170415-101830](https://cloud.githubusercontent.com/assets/794449/25064271/21b9e2ae-21c5-11e7-8e04-950b082eb550.jpg)

Also, more importantly, since the message that throw the exception was not processed, when the command is restarted,  it will try to re run it and an other exception is thrown.  Causing a uncontrolled exception loop!

Have a good day,
Samuel

**Comment by mkudelya** [comment]
Hi

The message after an exception is re-queued and put at the end of the queue with some delay. So after restarting it would not throw an exception immediately, it will process several more messages first.

If an exception is thrown again and again it means there's a bug or misconfig or something like that, It requires some admin or developer help.

The queue itself guarantees a messages is processed. So it tries to process it again and again.

**Comment by vtsykun** [comment]
Hi,
I guess it's better to limit the maximum number that a message can be re-queued. If the error is repeated several times, why is it not happen later. For example, not available smtp, not available external api, deleted after update platform message queue processor сan block the work of MQ. Currently the only way to stop uncontrolled exception loop is delete all messages from the queue

**Comment by sadortun** [comment]
2.1 is no longer supported
