### ISSUE TITLE
How to assign an access level to a user? 

### ISSUE THREAD

**Issue by videni** [oroinc/platform#687]
This question might be a little  silly,   but I just can't connect AccessLevel , BusinessUnit, Organization together ， I have read [Security](https://www.orocrm.com/documentation/1.10/book/security)  several times , I know  an AccessLevel would  be assigned to a  user before we check his permission,  I look the code , the OneShotIsGrantedObserver  is used to get a user's access level ,  but when that access level is assigned?  

I think a more detail technical  document about OroSecurity Acl part would be great help.

**Comment by dnahrebecki** [comment]
Hello @videni,
permissions are assigned to roles only, not to users directly. So if you would like to have permissions assigned to some user, you need to assign role to him and then set all permissions that you'd like to this particular role. You can read more in https://www.orocrm.com/documentation/current/admin-guide/security/access-management-roles

**Comment by videni** [comment]
@dnahrebecki , thank for clarify the essence of role-permission relationship, it is easy to get confused when thing are complicate,  any materials that details how the EntityMaskBuilder works please?  

```
 /**
     * Determines how many permissions stored in one mask.
     * For service mask is used 32 bit integer value. We use five bits for each permissions in mask to store
     * all access levels (basic, local, deep, global, system). So 15 bits used for permissions data. The remaining 16
     * bits will be used as service bits (as we know, 31 bits we can use for data and 1 bit is used for sign) and we
     * have 65536 (2^16) unique combinations of masks.
     * Current constant value was selected based on optimal numbers of unique masks and better performance.
     */
``` 
I don't understand these comments fully. 

1.  How does AccessLevel is leveraged in EntityMaskBuilder? 
2. What is service  bit mask?

**Comment by dnahrebecki** [comment]
Security and permissions, in general, are not an easy tasks, but let me try to explain this using example.

Access Levels: system, global, deep, local, basic = 5. This number can't be changed, so it means we support exactly five access levels.
Example of permissions: VIEW, CREATE, EDIT, DELETE, ASSIGN, SHARE = 6
Maximum level of permissions in mask: 3
Let's assume that we have a system access level to all permissions.

So it means that we will have 2 masks ( 6 permission / 3 max permissions in mask = 2)
(...) 00 10000 10000 10000 (service id 1: system for VIEW, system for CREATE, system for EDIT)
(...) 01 10000 10000 10000(service id 2: system for DELETE, system for ASSIGN, system for SHARE)

Service bit mask is an ID/number of mask builder that will be used for building masks to check ACLs by & operation. It indicates which permissions are stored in which mask (have a look at https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/SecurityBundle/Acl/Extension/EntityAclExtension.php#L560).

**Comment by videni** [comment]
@dnahrebecki ,    thank you , very appreciate.

```
(...) 00 10000 10000 10000 (service id 1: system for VIEW, system for CREATE, system for EDIT)
(...) 01 10000 10000 10000(service id 2: system for DELETE, system for ASSIGN, system for SHARE)
```

Assume we separate ` (...) 00 10000 10000 10000` into two parts:
1.  (...) 00
2.  10000 10000 10000

Does this mean the first part is for service bits(access level) , the second 15 bit is for permission data , is the second part alway the fixed value `10000 10000 10000`, will not change to `11000 10000 10000` ?  apparently what I thought is wrong , something is missing in my head . 

 >For service mask is used 32 bit integer value. We use five bits for each permissions in mask to store
 all access levels (basic, local, deep, global, system). So 15 bits used for permissions data. The remaining 16  bits will be used as service bits (as we know, 31 bits we can use for data and 1 bit is used for sign) and we  have 65536 (2^16) unique combinations of masks.

Oro defined 5 permissions, no `share` defined. can you use this as example please?
```
oro_permissions:
    VIEW: []
    CREATE: []
    EDIT: []
    DELETE: []
    ASSIGN: []
```
sorry for that I can't connect your example to Oro actual implementation.

**Comment by dnahrebecki** [comment]
First part is for service bits, second is for access levels of given permissions. From the example above `10000 10000 10000` means `system, system, system` access level for some permissions. within each of 5 bits you'll have only one `1` (can be one of: 10000, 01000, 00100, 00010, 00001 - all of our access levels).
Let's use your example. You have 5 permissions, which means that you'll have 2 masks (cause only 3 permissions can be stored in one mask):
```
01 xxxxx xxxxx xxxxx
00 00000 xxxxx xxxxx
```
xxxxx - means access level for given permission. I'm not sure about order, but it should be like:
```
01 xxxxx(EDIT) xxxxx(CREATE) xxxxx(VIEW)
00 00000 xxxxx(ASSIGN) xxxxx(DELETE)
```
and let's assume that you have LOCAL access level for all of permissions, so:
```
01 00010(EDIT) 00010(CREATE) 00010(VIEW)
00 00000 00010(ASSIGN) 00010(DELETE)
```

**Comment by videni** [comment]
@dnahrebecki,  thank you very much , I got it ,  this is a very good start point for me  to study further .

**Comment by videni** [comment]
@dnahrebecki,   for EntityMaskBuilder , it has following constants defined, 
```
const SERVICE_BITS        = -32768; // 0xFFFF8000
 const REMOVE_SERVICE_BITS = 32767;  // 0x00007FFF
```
why its SERVICE_BITS is -32768?  for FieldMaskBuilder, its SERVICE_BITS is -2048 ？why these values are selected ?
