### ISSUE TITLE
Use system mailbox as default sender?

### ISSUE THREAD

**Issue by VinnyVicious** [oroinc/platform#689]
Right now, Oro uses the user account email configuration to send emails to contacts. Is it possible to have a single mailbox for everyone? Send all emails from mailer@mydomain.com.

**Comment by artml** [comment]
@VinnyVicious yes, just create a [system mailbox](https://www.orocrm.com/documentation/2.0/admin-guide/email/system-mailboxes) and share it to all your users. And don't create personal mailboxes.

**Comment by VinnyVicious** [comment]
Does that have to be done on a per-user basis?
