### ISSUE TITLE
2.1: saving Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue throw an exception.

### ISSUE THREAD

**Issue by dimonixx** [oroinc/platform#690]
Oro\Bundle\LocaleBundle\Entity\LocalizedFallbackValue#localization' that was not configured to cascade persist operations for entity: English. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist this association in the mapping for example @ManyToOne(..,cascade={"persist"}).

**Comment by mkudelya** [comment]
Hi @dimonixx 

Thank you for reporting the issue! Could you write the steps to reproduce, please?

**Comment by dimonixx** [comment]
I've setup several locales. The exception was thrown as i tried to hide a menu item in the menu editor.

**Comment by mkudelya** [comment]
Hi

I'm using version 2.1.0 of orocrm. I have created two localizations:

![06669eb2c74e4bcd906da02ebfe871e4](https://cloud.githubusercontent.com/assets/3332593/25953206/544ad768-366b-11e7-92c9-97b171907b85.png)

and hid the 'My calendar' menu:

![6234c534f7424b61b5fae8ef99872f3a](https://cloud.githubusercontent.com/assets/3332593/25953278/8ec03e1a-366b-11e7-8a2e-d151abff971d.png)

but i had no errors. More detailed steps to reproduce may be very helpful.

Thank you!

**Comment by manowark** [comment]
I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
