### ISSUE TITLE
How to detect tenant ? 

### ISSUE THREAD

**Issue by videni** [oroinc/platform#691]
# 1. For tenant(Organization) Administrator:

the `organization-form-login` will automatically load the organization for current user

# 2. For customer

Assume organization A has unique domain  `ww. a.com` , a customer doesn't know his organization , he only know the domain , when he accesses `www.a.com`,   we should resolve the corresponding organization.   any reliable way to do this? 

# Solution I can think

resolve organization based on request,  and  inject that organization instance into service container，this service is so called `synthetic services` in Symfony.

## Problem:

1.  need to differentiate admin and customer.   

when the url starts with：
(1) `/admin`

use `organization-form-login` to detect organization

(2) `/`

use domain to detect organization

# Question

how  to make them more consistent?  I am new to this business ,  can you give me some ideas please?

**Comment by mkudelya** [comment]
Hi @videni 

As i understand you have the one OroCRM instance with many organizations/virtual hosts and have possible use-cases:

- When a user go to www.AAA.com, the system should automatically switch to the AAA organization after login in case when user can access to the organization.
- When a user go to www.first.com/admin the system should work as usual.

- Do you use OroCRM or OroCommerce ?

**Comment by videni** [comment]
@mkudelya , Thanks for reply, I have seen your head portrait  many places,  in Sylius repo , OroPlatform repo， and Oro forum, your head portrait looks like a saver to me, haha.   we are developing a multitenancy SAAS platform , oro platform seems a good choice.  I am not using OroCRM or OroCommerce right now,  but OroCRM we might try to use a few months later.  

Does OroPlatform have an existing solution for tenant detect with sub domain, or dedicated domain?

**Comment by DimaSoroka** [comment]
hi @videni 
Multiple organization support is part of our enterprise edition offering and tenant detection with sub domains is something we can help you to solve there. Please let me know if you interested to continue conversation with our technical consulting and support team.

**Comment by vbyndych** [comment]
It seems that this question is answered, please feel free to reopen if you need more info
