### ISSUE TITLE
ImportExport Custom ImportType is not passed to body message queue

### ISSUE THREAD

**Issue by geoffroycochard** [oroinc/platform#695]
Hi,

How can i retrieve selected [custom ImportType](https://github.com/orocrm/platform/blame/master/src/Oro/Bundle/ImportExportBundle/Resources/doc/reference/how-to-use.md#L475) datas in the [message queue body](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ImportExportBundle/Controller/ImportExportController.php#L167), and [options](https://github.com/orocrm/platform/blob/2.1.0/src/Oro/Bundle/ImportExportBundle/Async/Import/HttpImportMessageProcessor.php#L118) ?

**Comment by alex-n-2k7** [comment]
@geoffroycochard, 
Could you please provide more details about what exactly you are trying to achieve?
And I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
