### ISSUE TITLE
Something like recent email

### ISSUE THREAD

**Issue by fsabeti** [oroinc/platform#696]
Hi everybody,

I want to make a feature like recent email feature. I Understand that I need an action like `placeholderLastAction` and a twig like `OroEmailBundle:Notification:button.html.twig`. I want to know how does the `clank_server` works. How can I implement a feature that send a message or notification to the client using clank_server?

P.S: I know how does [this simple chat-room project ](https://github.com/JDare/ClankChatBundle) works.

Thanks in advance.

**Comment by ahmadgolzar** [comment]
Hi,

I also want to know how the clank server works and how can I use it to implement new features. Has anyone used it before. Are there any tutorial or documentation?

Thanks

**Comment by mkudelya** [comment]
Hi

Here is a small [tutorial](https://gist.github.com/mkudelya/32e2bad7a8db5963cfcfafb30e5fea55) on how to use the clank server. The SendClankMessageCommand is a regular symfony command which sends certain data to my_unique_channel channel (topic), view.html.twig is a view template of the UserBundle. I have added only the clankWidget variable into it.

**Comment by fsabeti** [comment]
Thank you so much
