### ISSUE TITLE
JDare/ClankBundle does not have a commit during 4 years (since 2013), and is not compatible with the new Ratchet releases (0.3.x, 0.4.x), consider remove dependency on it and use Ratchet directly 

### ISSUE THREAD

**Issue by dmitry-fedyuk** [oroinc/platform#699]
https://github.com/JDare/ClankBundle/commits/master
https://github.com/JDare/ClankBundle/blob/0.1.6/composer.json#L18
![07](https://cloud.githubusercontent.com/assets/83204/26281115/a8b831e2-3df5-11e7-9265-1d71317f58a4.png)

**Comment by dmitry-fedyuk** [comment]
https://github.com/JDare/ClankBundle/issues/43

**Comment by alex-n-2k7** [comment]
Thank you for reporting this issue.The internal task to fix this problem (Internal ID: BAP-13053).

**Comment by anyt** [comment]
Switched to `gos/web-socket-bundle`
https://github.com/oroinc/platform/blob/eda28b5d60c333ca99819d467b154a65fadb0dd5/composer.json#L52

Thank you for contribution!
