### ISSUE TITLE
Personal email visible in listing for other users

### ISSUE THREAD

**Issue by ollieno** [oroinc/platform#705]
When configuring per user email imap sync, all mail will show up in the "my email > All Email" section for each user. 

User A can see user B personal email listing (user A is not listed as to/cc/bcc..) 
User B can see user A personal email listing (user B is not listed as to/cc/bcc..) 

When user A clicks on an email which he shouldn't see, he do gets a 
"You do not have permission to perform this action."

**Comment by NiMias** [comment]
@ollieno , Thank you for reporting the issue!

We've already fixed this problem in platform versions 2.2.0, 2.1.3, 2.0.11 (and newer, respectively).
So, if version of your OroPlatform is earlier then mentioned above - please, make the upgrade.

If version of your OroPlatform is newer - please, provide an exact OroPlatfrom version, that you're using.

(You can find out the version on the page /platform/information of you Oro application)

**Comment by ollieno** [comment]
Thx! I just noticed. Works like a charm!
