### ISSUE TITLE
The field name's validator's messsage «This value should contain only alphabetic symbols, underscore and numbers» is semantically wrong because it does not mention that it is forbidden to start a name with an underscore

### ISSUE THREAD

**Issue by dmitry-fedyuk** [oroinc/platform#707]
![](https://oplatform.club/uploads/default/original/1X/299a4c79d5d74dbc9329d4b2306906a0da48c7ee.png)

**Comment by mkudelya** [comment]
@vsoroka 

I think we should replace this message to "This value should contain only alphabetic symbols, underscore and numbers and should starts from alphabetic symbols". What do you think ?

https://github.com/orocrm/platform/blob/2.2.0/src/Oro/Bundle/EntityExtendBundle/Resources/config/validation.yml#L16-L17

**Comment by manowark** [comment]
Message was updated in 2.2 version.

I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
