### ISSUE TITLE
Security issue: the API keys are stored in the database as a plain text and are used without a salt

### ISSUE THREAD

**Issue by dmitry-fedyuk** [oroinc/platform#708]
![](https://oplatform.club/uploads/default/original/1X/1a518de1995a81fb6e137dcc16c3d0b5e3b4b20c.png)
[security.stackexchange.com/questions/38566](https://security.stackexchange.com/questions/38566)

**Comment by NiMias** [comment]
Thank you for reporting the issue!
I've created an task for fix (internal code BAP-14910). It will be fixed soon.

**Comment by vsoroka** [comment]
fixed in all versions since 1.10
