### ISSUE TITLE
Warning: Illegal string offset 'value' in 

### ISSUE THREAD

**Issue by SHABU89** [oroinc/platform#710]
I have written a PHP code in that 
	$sStartDate = date("Y-m-d",strtotime($feed['DTSTART']['value']));  
	$sEndDate = date("Y-m-d", strtotime($feed['DTEND']['value']));

It shows the above two lines as Warning: Illegal string offset 'value' in 
How can i fix this issue

**Comment by ephrin** [comment]
Your data under `$feed['DTSTART']` is a string.
String chars can be accessed by offset number (like an array).
For example.
```
$string = 'Hello World';
print($string[0]);
print($string[6]);
```
Will print first letters from words of the string, as they appears there starting count from 0.

Seems like it is not an issue of the platform, but lack information.

Vote. We should close it.

**Comment by sokal32** [comment]
It is not an issue of the platform, I'm closing this issue. If you are sure that this is issue of platform, reopen this issue and provide some additional information
