### ISSUE TITLE
Autocomplete problem

### ISSUE THREAD

**Issue by fsabeti** [oroinc/platform#711]
Hi everyone,
I create an autocomplete but it does not work. These are what I did to create an autocomplete:

I put this annotation above the entity:
`       "form"={`
`           "form_type"="s_doc_person_select",`
`           "grid_name"="person_select-grid",`
`      }`

I have grid named "person_select-grid" that works fine.

I made a select type by completing these function below:
`public function configureOptions(OptionsResolver $resolver)`
`    {`
`        $resolver->setDefaults(`
`            [`
`                'autocomplete_alias' => 's_person',`
`                'configs' => [`
`                    'placeholder' => 's.person.form.choose',`
`                    'result_template_twig'    => 'SDocManagmentBundle:Person:searchResult.html.twig',`
`                ],`
`            ]`
`        );`
`    }`
``
`    public function getName()`
`    {`
`        return 's_doc_person_select';`
`    }`
``
`    public function getParent()`
`    {`
`        return 'oro_entity_create_or_select_inline';`
`    }`
``

I made a search.ym in config/oro/ like below:

`search:`
`    SDocManagmentBundle\Entity\Person:`
`        alias: s_person`
`        label: s_person.entity_plural_label`
`        route:`
`            name: s_person_view`
`            parameters:`
`                id: id`
`        search_template: SDocManagmentBundle:Person:searchResult.html.twig`
`        title_fields: [personName]`
`        mode: normal`
`        fields:`
`            -`
`                name:                   personName`
`                target_type:            text`
`                target_fields:          [personName]`

I made two below services in service.yml:

`    s_doc_managment.form.type.person_select:`
`        class: %s_doc_managment.form.type.person_select_type.class%`
`        tags:`
`            - { name: form.type, alias: "s_doc_person_select" }`
`    s_doc_managment.form.autocomplete.s_person.search_handler:`
`         parent: oro_form.autocomplete.search_handler`
`         arguments:`
`             - %s_doc_managment.entity.person.class%`
`             - ["personName"]`
`         tags:`
`             - { name: oro_form.autocomplete.search_handler, alias: s_person, acl_resource: ``s_person_view }`

I made a twig with code below:

`{% extends 'OroSearchBundle:Search:searchResultItem.html.twig' %}`

`{% set showImage = false %}`

`{% set recordUrl = indexer_item.recordUrl %}`
`{% set title = indexer_item.recordTitle %}`
`{% set entityType = 's_person.entity_label'|trans %}`

`{% set entityInfo = [`
`{'title': 'oro.ui.created_at'|trans, 'value': entity.createdAt ? entity.createdAt|oro_format_datetime : `'N/A'},`
`{'title': 'oro.ui.updated_at'|trans, 'value': entity.updatedAt ? entity.updatedAt|oro_format_datetime : ``'N/A'},`
`] %}`

I used oro:search:reindex command and clear cache but it did not work. acutally I can see the field but it does not work properly. I looked at oro_search* tabel in data base and there were no records in it.

What should I do?
Thank you so much.

**Comment by d-beekeeper** [comment]
Hi fsabeti.
Did you tried to start a message queue consumer?
php app/console oro:message-queue:consume -vvv
??
Start it, wait for some time and then re-try.

**Comment by fsabeti** [comment]
Hi,
I used this command and it works fine. There is another problem. /when I activate the create route which I mean adding `'create_form_route' => 's_person_create',` to type class, it says there is no such a rout but, I'm sure there is such a route as I use it somewhere else.
What should I check or do?
Thanks in advance.

**Comment by aivus** [comment]
Hi, @fsabeti.

Try to execute `app/console debug:router | grep s_person_create` it should show you your route.
If it returns something that means route is present. Otherwise, that means Symfony doesn't see your route.

**Comment by fsabeti** [comment]
Hi @aivus 

I did what you said. It returned something and there is such a route. What should I do in this case?

**Comment by aivus** [comment]
> it says there is no such a rout but, I'm sure there is such a route as I use it somewhere else.
> It returned something and there is such a route.

That means route exist in your system.

Try to look on examples in orocommerce:
https://github.com/orocommerce/orocommerce/blob/21aa88dc0994abfd3328606e1ae92537d67530f6/src/Oro/Bundle/PaymentTermBundle/Form/Type/PaymentTermSelectType.php#L22

https://github.com/laboro/dev/blob/126749a53b9ea23da179476094d2e2a6d25c50a6/package/commerce/src/Oro/Bundle/PaymentTermBundle/Controller/PaymentTermController.php#L56-L56

**Comment by fsabeti** [comment]
Thank you @aivus , I checked every single detail several times. It did not work and I get the same error. In the debug mode of chrome I see 

> Uncaught Error: The route "s_person_create" does not exist.

in the console

**Comment by aivus** [comment]
@fsabeti could you show me what this command returns?

`app/console debug:router | grep s_person_create`

**Comment by fsabeti** [comment]
@aivus 
Sure.

>  s_person_create                                       ANY        ANY      ANY    /person/create 

this is it.

**Comment by aivus** [comment]
@fsabeti try to clear caches by `app/console cache:clear --env=<env>`, where `<env>` it's your environment (dev/prod).

It looks strange, because route exists but some part of system doesn't see it.

**Comment by sprightly** [comment]
Issue closed as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
