### ISSUE TITLE
Filters: Equals \ Exact Time

### ISSUE THREAD

**Issue by alex-mak** [oroinc/platform#713]
Hi ORO team,

On User listing page tried to filter by Created At (Updated At, Last Logged In) using 'equals' filter. 
![image](https://user-images.githubusercontent.com/6999236/27333391-604519ac-55ce-11e7-8e52-d702b14c8275.png)

There are no results found when exact time (hh:mm) is entered

**Comment by sadortun** [comment]
Have you tested with a timeline offset ? Maybe the search is performed in local time while the DB is stored in GMT ?

**Comment by alex-mak** [comment]
Issue is reproduced on demo. 
Anyway, checked -- it's not a timeline offset. It looks exact seconds (may be 00) is used in query instead of time interval
![demo](https://user-images.githubusercontent.com/6999236/27379705-01f84fce-5685-11e7-970c-9ad8b9c9fe92.gif)

**Comment by sokal32** [comment]
Thank you for reporting the issue! We greatly appreciate all contributions to Oro projects.
I've created ticket to fix this bug with ID BAP-15209
