### ISSUE TITLE
Send emails via message queue?

### ISSUE THREAD

**Issue by VinnyVicious** [oroinc/platform#722]
I'm current using `Oro\Bundle\EmailBundle\Mailer\Processor::process` to send emails from my services. Unfortunately, in some cases, the operation is slow so i'm considering using the message queue. Is there a built-in service that sends emails asynchronously? Any documentation on that?

**Comment by aivus** [comment]
Hi @VinnyVicious 

Take a look at [SendEmailMessageProcessor](https://github.com/orocrm/platform/blob/50047c1d8abc5f811d0db759b501b8d27b0bff65/src/Oro/Bundle/NotificationBundle/Async/SendEmailMessageProcessor.php).

Example of adding message to queue could be found here:
https://github.com/orocrm/platform/blob/50047c1d8abc5f811d0db759b501b8d27b0bff65/src/Oro/Bundle/NotificationBundle/Manager/EmailNotificationSender.php
