### ISSUE TITLE
Updating contacts via the API continuously re-display "× Content of the page is outdated..."

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#724]
Hi Oro Team,

We are updating about 100k contacts via the API in the background and the notification continiously appear and disapear.
> Content of the page is outdated, please refresh the page Customers/ Contacts"

# Current behaviour 
![orocrm-bug-access-via-api](https://user-images.githubusercontent.com/794449/28047060-c6cd26aa-65b5-11e7-9bc3-bebbe592067d.gif)

# Expected behaviour
If the notification is already visible,  leave it visible, and do not  show it multiple times.

# How to reproduce
Update many contacts via the API.

**Comment by mbessolov** [comment]
Thank you for reporting the issue.
(Internal ID - BAP-15023)

**Comment by vsoroka** [comment]
The issue was fixed in the master branch and will be available since version 2.6
