### ISSUE TITLE
Sorting by Tag Taxonomy fail.

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#726]
Hi Oro Team,

On `/tag`  sorting by taxonomy produce an error
![image](https://user-images.githubusercontent.com/794449/28151479-c74c4a84-6768-11e7-9966-62d8ebbf67e0.png)

>>>
Uncaught PHP Exception Doctrine\ORM\Query\QueryException: "[Semantical Error] line 0, col 264 near 'tagTaxonomy.name': Error: 'tagTaxonomy' is not defined." at /vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php line 63
>>>

**Comment by mbessolov** [comment]
Thank you for reporting the issue.

Internal ID: BAP-15034

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/platform/commit/c2ccc4805c9d41fc01f31961bcea9700056c6408.

Thank you for contribution!
