### ISSUE TITLE
Export not working after change count of related entities

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#728]
Hi guys,
I found bug with export. Before MQ export work fine, but after, it was broken. It occurs due to local caching of  `backendHeader` in [ConfigurableTableDataConverter](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ImportExportBundle/Converter/ConfigurableTableDataConverter.php) 

**STR**

0) Affect version 2.0 - master
1) Install orocrm application without demo data
2) Run 1 consumer
3) Create 1 Lead with 1 address
4) Export leads. You will see email that export performed successfully
5) Add second address for lead
6) Run again export of lead

**Actual**: An error occurs
```
Export operation failed, 1 error(s) found.
<a href=http://example.com/import_export/job-error-log/618.log target=_blank>Error log</a>
```
Logs:
```
batch.ERROR: Encountered an error executing the step: Backend header doesn't contain fields: addresses:1:firstName, addresses:1:label, addresses:1:lastName, addresses:1:country:iso2Code [] []
```

Of course, if I restart consumer after first export, it will work normal.

Thanks

**Comment by alex-n-2k7** [comment]
Hi @vtsykun,
Thank you for reporting the issue.
Internal ID: CRM-8387

**Comment by dyarmolinsky** [comment]
cc @alfredoka

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/platform/commit/c57aeec596f02fe4124eed26dffde22fe332357a.

Thank you for contribution!
