### ISSUE TITLE
Unnecessary slow count queries while import

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#729]
Hi Oro team,
We noticed that before import starts, some count queries run on database that match on full table (millions of records)
```
LOG: duration: 45720.034 ms statement: SELECT COUNT(c0_.id) AS sclr_0 FROM orocrm_sales_lead c1_ INNER JOIN orocrm_sales_lead_address c0_ ON c1_.id = c0_.owner_id GROUP BY c1_.id ORDER BY sclr_0 DESC LIMIT 1
LOG: duration: 25469.355 ms statement: SELECT COUNT(c0_.id) AS sclr_0 FROM orocrm_sales_lead c1_ INNER JOIN orocrm_sales_lead_email c0_ ON c1_.id = c0_.owner_id GROUP BY c1_.id ORDER BY sclr_0 DESC LIMIT 1
LOG: duration: 38908.090 ms statement: SELECT COUNT(c0_.id) AS sclr_0 FROM orocrm_sales_lead c1_ INNER JOIN orocrm_sales_lead_phone c0_ ON c1_.id = c0_.owner_id GROUP BY c1_.id ORDER BY sclr_0 DESC LIMIT 1
```
This queries needed to get the headers that are used when exporting, but are not used when importing. But this [method](https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/ImportExportBundle/Converter/ConfigurableTableDataConverter.php#L166) returns the headers for import and export together, so there are performance problems while importing. Of course, there is local caching of it headers, (see issue https://github.com/orocrm/platform/issues/728) but consumers over and over again restarted by memory limit, so 80% import time lost on slow unnecessary queries

Thanks,
Vladimir

**Comment by manowark** [comment]
Thank you for reporting issue.

Internal ID: CRM-8387

**Comment by dyarmolinsky** [comment]
cc @alfredoka

**Comment by vtsykun** [comment]
It was fixed, thanks!
