### ISSUE TITLE
Unique constraint on "oro_email_address" affected a parallel import with 4 consumers 

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#730]
Hi Oro team,
This problem concerns those entities that use EmailOwner functionality form EmailBundle, for example it is `OroContactBundle:Contact` and `OroUserBundle:User`. But if I will use only one consumer it will work fine, like in https://github.com/orocrm/platform/issues/725

**STR**

1) Install orocrm application
2) Clear tables orocrm_contact and oro_email_address
3) Prepare contact import file with 1000 records, so that the any count of same email addresses are repeated in it. (You can use this *.csv file https://raw.githubusercontent.com/vtsykun/file-storage/master/contacts.csv)
4) Run 4 consumers
5) Import file

**Actual**
3 consumers interrupted by exception. Only 300 of 1000 records was import
```
The EntityManager is closed.
The EntityManager is closed.
The EntityManager is closed.
The EntityManager is closed.
The EntityManager is closed.
An exception occurred while executing 'SELECT o0_.id AS id_0 FROM oro_email o0_ INNER JOIN oro_email_recipient o1_ ON o0_.id = o1_.email_id INNER JOIN oro_email_address o2_ ON o1_.email_address_id = o2_.id WHERE o2_.owner_contact_id = ? AND o2_.has_owner = ? LIMIT 1' with params [277, 1]:

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
An exception occurred while executing 'SELECT o0_.id AS id_0 FROM oro_email o0_ INNER JOIN oro_email_recipient o1_ ON o0_.id = o1_.email_id INNER JOIN oro_email_address o2_ ON o1_.email_address_id = o2_.id WHERE o2_.owner_contact_id = ? AND o2_.has_owner = ? LIMIT 1' with params [177, 1]:

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
```
**Expected**
All records should be import without errors

**Comment by alex-n-2k7** [comment]
Hi @vtsykun,
Thank you for reporting the issue.
Internal ID: CRM-8385

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/platform/commit/e97fcfb1646daf1cdd1de64cdca808638127a2c1.

Thank you for contribution!
