### ISSUE TITLE
Unable to create a segment with the same name for different organizations

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#734]
**STR**
1) Create two organization
2) Create the segment with name "test" as administrator from first organization
3) Login as administrator from second organization
4) Create the segment with name "test"

Actual: An error occurred "Segment name already in use". But administrator from second organization not see segment with name "test"

**Comment by anyt** [comment]
Hi @vtsykun 

All questions related to Enterprise version should be addressed to our Customer Support Portal - http://support.orocrm.com

Thank you !

**Comment by vtsykun** [comment]
I understood, 
Thank you
