### ISSUE TITLE
Oro tag enabled for update view

### ISSUE THREAD

**Issue by NikDevPHP** [oroinc/platform#739]
Hi, after update oro platform (2.3.0) tags stopped working on edit view. Please tell me how to make them correctly now.

**Comment by aivus** [comment]
Hi, @NikDevPHP 

Could you write some STR?

**Comment by NikDevPHP** [comment]
Hi, @aivus 
Just ask to write a detailed instruction on how to connect the tags to the entity. I think this is due to Form type, I added, 
` ->add(
                'tags',
                'oro_tag_select',
                ['label' => 'Tags']`
 but have error on entity update page, see attach
![tag_error](https://user-images.githubusercontent.com/11384994/29557027-7b2ec7c0-8730-11e7-9d94-75ef493a9a91.png)

**Comment by manowark** [comment]
Hi, @NikDevPHP.

Please, give your way how you added tag to your entity. It seems something went wrong.
Try to add
```
 *          "tag"={
 *              "enabled"=true
 *          },
```
to annotation of your entity. Like https://github.com/oroinc/crm/blob/master/src/Oro/Bundle/ContactBundle/Entity/Contact.php#L74-L76.

Next run command to update all related configurations and cache of your application
```
php app/console oro:platform:update --force --env=prod
```
After that on entity view page and entity grid you should have field for choose tags.

Also, please read https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/TagBundle/README.md

**Comment by alex-n-2k7** [comment]
@NikDevPHP, I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
