### ISSUE TITLE
The JS errors occurred on locale: "es_ES"

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#740]
After update platform on v2.3 some JS date-time functionality working not correctly on `es_ES` locale

STR:
1)Set `locale: es_ES`  in parameters.yml and install OroPlatform v2.3.1

**Case 1**: Js validations are showing on valid data
For example try to set "Birthday" for user http://ex.com/user/create
![selection_122](https://user-images.githubusercontent.com/21358010/29579002-0b3196d8-877a-11e7-96c3-38729983f4ab.png)

**Case 2** Due date not saved for Task, but on "en" locale it working fine
![selection_123](https://user-images.githubusercontent.com/21358010/29579074-44f5d71c-877a-11e7-8923-c51b6e73e24f.png)
![selection_124](https://user-images.githubusercontent.com/21358010/29579078-480f5c20-877a-11e7-9305-9e8168c17c7e.png)

**Comment by Grygir** [comment]
Hello @vtsykun 
Thank you for the bug report. It'll be fixed within next bug fix release.

**Comment by manowark** [comment]
INTERNAL ID: BAP-15311

**Comment by vtsykun** [comment]
Thank you @Grygir. It is works fine!
