### ISSUE TITLE
one to many attachment migration

### ISSUE THREAD

**Issue by ahmadgolzar** [oroinc/platform#741]
Hi,

I need to add attachment and note to an entity of ours by integration with same functionality as when I add attachment and note with "entity manager". How should I do it?
With migration I just get single attachment in my entity. I can't add several attachments or notes.

Please help.
Thanks

**Comment by vbyndych** [comment]
Hi @ahmadgolzar,
Am I right that you've tried approach described in [AttachmentBundle manual](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/AttachmentBundle/readme.md#migration-extension-usage-example) in the second example and [ActivityByndle](https://github.com/oroinc/platform/tree/master/src/Oro/Bundle/ActivityBundle#how-to-enable-activity-association-using-migrations)? So your migration looks like this [attachment migration](https://github.com/oroinc/crm/blob/master/src/Oro/Bundle/SalesBundle/Migrations/Schema/v1_7/OpportunityAttachment.php) or this [note migration](https://github.com/oroinc/crm/blob/master/src/Oro/Bundle/SalesBundle/Migrations/Schema/v1_5/OroSalesBundle.php).
This way you can add attachments and notes functionality to almost any entity in the system. If you've tried it and it doesn't work for you, could you add more details about platform version you've used and probably some code from your migration, so we can investigate a problem.

Thank you in advance.

**Comment by ahmadgolzar** [comment]
Thank you so much for your reply and the samples. It was exactly what we needed for attachment and note migration.
We had misunderstood the relation the migration was providing. It is exactly one to many relation we need.

Thanks again.
Ahmad
