### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by vafabandi** [oroinc/platform#744]
hi everyone,
My problem is that to use oro_entity_create_or_select_inline create don't work and say this route does not exists, but I know this route is exist and work good.
This problem was as same as fsabeti's problem in another issue.
thanks.

**Comment by sprightly** [comment]
Hello, vafabandi.

Please recheck this in dev env. Also ensure that you cleared the cache before this, with `app/console cache:clear env dev`.

If I correctly understood, you have issue similar to the #711. When you click "+\create" you see next in browser's console log:
> Uncaught Error: The route "your_rote" does not exist.

This error usually fired in prod env for wide range of issues with requested route. In dev env, you'll be able to see problematic request in browser's Network panel and investigate response, maybe here is some error during widget rendering or so.

**Comment by alex-n-2k7** [comment]
@vafabandi,  I am now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
