### ISSUE TITLE
Loading permissions for workflow transition using AbstractLoadAclData fails

### ISSUE THREAD

**Issue by dimonixx** [oroinc/platform#747]
Trying to load a permission like `workflow:workflow_name::transition_name|step_1|step_2`

fails, at line [94](https://github.com/oroinc/platform/blob/cbb717f36f4da52ecc2f205e629b6ba7bbcfe7ee/src/Oro/Bundle/SecurityBundle/Migrations/Data/ORM/AbstractLoadAclData.php#L94)   `$oid = $aclManager->getOid(str_replace('|', ':', $permission));`

The `WorkflowTransitionAclExtension` throws LogicException as `getObjectIdentity` method is not supported.
How to load wrokflow transition permissions ? Using the `WorkflowTransitionMaskBuilder` and setting the permission through `AclManager` ? In that case what should be `oid` ?

**Comment by alex-n-2k7** [comment]
Hi @dimonixx 

Unfortunately, for now, its not clear that exactly you are trying to do.
The described error message is, unfortunately, not enough to understand what is wrong. 
Please explain the problem you are trying to solve in more details.
Or provide us a code example.

**Comment by dimonixx** [comment]
I'm trying to save a permission for Transition `workflow:workflow_name::transition_name|step_1|step_2`.

Using this class [Oro\Bundle\SecurityBundle\Migrations\Data\ORM\AbstractLoadAclData](https://github.com/oroinc/platform/blob/1a6a7076c2f1ad395b9fb59031c0f7836def02b4/src/Oro/Bundle/SecurityBundle/Migrations/Data/ORM/AbstractLoadAclData.php) in the same way as hier [Oro\Bundle\UserBundle\Migrations\Data\ORM\AddProfileAndConfigUpdateCabalitiesToRole](https://github.com/oroinc/platform/blob/1a6a7076c2f1ad395b9fb59031c0f7836def02b4/src/Oro/Bundle/UserBundle/Migrations/Data/ORM/AddProfileAndConfigUpdateCabalitiesToRoles.php).

```
protected function getAclData()
    {
        return [
            self::ALL_ROLES => [
                'permissions' => [
                    'workflow:workflow_name::transition_name|step_1|step_2'  =>['PERFORM_TRANSITION']
                ],
            ],
        ];
    }
```

**Comment by alex-n-2k7** [comment]
Hi @dimonixx 

have looked in yours example, 
so, you need to override the method 'processPermission' a bit
to get the OID you need the part of permission string before '::', e.g. 'workflow:workflow_name'
and instead of '$aclManager->setPermission' you need to use '$aclManager->setFieldPermission'
so, the quick example will look like this:

```
<?php

namespace Oro\Bundle\UserBundle\Migrations\Data\ORM;

use Symfony\Component\Security\Acl\Model\SecurityIdentityInterface;

use Oro\Bundle\SecurityBundle\Acl\Persistence\AclManager;
use Oro\Bundle\SecurityBundle\Migrations\Data\ORM\AbstractLoadAclData;

class Test extends AbstractLoadAclData
{
    /**
     * {@inheritdoc}
     */
    public function getDataPath()
    {
        return '';
    }

    /**
     * {@inheritdoc}
     */
    protected function getAclData()
    {
        return [
            self::ALL_ROLES => [
                'permissions' => [
                    'workflow:task_flow::start_progress|open|in_progress' => ['PERFORM_TRANSITION_NONE'],
                ]
            ],
        ];
    }

    protected function processPermission(
        AclManager $aclManager,
        SecurityIdentityInterface $sid,
        $permission,
        array $acls
    ) {
        $permission = explode('::', $permission);
        //$oid = $aclManager->getOid(str_replace('|', ':', $permission));
        $oid = $aclManager->getOid($permission[0]);

        $extension = $aclManager->getExtensionSelector()->select($oid);
        $maskBuilders = $extension->getAllMaskBuilders();

        foreach ($maskBuilders as $maskBuilder) {
            $mask = $maskBuilder->reset()->get();

            if (!empty($acls)) {
                foreach ($acls as $acl) {
                    if ($maskBuilder->hasMask('MASK_' . $acl)) {
                        $mask = $maskBuilder->add($acl)->get();
                    }
                }
            }

            //$aclManager->setPermission($sid, $oid, $mask);
            $aclManager->setFieldPermission($sid, $oid, $permission[1], $mask);
        }
    }
}
```

**Comment by dimonixx** [comment]
Hi Alex,

I‘ve solved it the similar way. 
Thank you.
