### ISSUE TITLE
Problem with submitting "OroBirthdayType::class"  type or "oro_datetime" form field

### ISSUE THREAD

**Issue by morozovalexander** [oroinc/platform#748]
When I select date in datepicker hidden date field still empty and sending without new value. Both in my custom form or in [oro task bundle](https://github.com/oroinc/OroCRMTaskBundle), when I try to select dueDate throw datetimepicker. There were no problems in 2.2 version, and problem was found while upgrade to 2.3 version. I use [platform-application](https://github.com/oroinc/platform-application) for my project base.
![image_from_skype](https://user-images.githubusercontent.com/7498526/30197006-031d15fe-948f-11e7-92df-4e573321079c.png)

**Comment by yaroslavbr** [comment]
Thank you for reporting the issue!  I can not reproduce problem with date-picker on standard application. Maybe is is related to localisation somehow. This requires additional investigation, I will get back to you as soon as possible with the answer. Thank you for your patience!

**Comment by morozovalexander** [comment]
Thank you for quick answer. I tried to reproduce problem by cloning platform-application 3.3 version and creating custom bundle with test entity contained datetime field and got not the same error. Maybe it is only my application and ru_RU localisation problem.

**Comment by sprightly** [comment]
I am now closing this issue as it seems clarified. Please, feel free to reopen it if you have any questions.

**Comment by morozovalexander** [comment]
it seems like all is ok with localized datepicker in 2.6 version
