### ISSUE TITLE
Tag Filter is displayed wrong

### ISSUE THREAD

**Issue by alex-mak** [oroinc/platform#750]
Hi all, 
noticed a bug about tag filter after update the platfrom from v2.2 to v2.3 (possibly, the issue already existed but never be sumbitted by our team):

Steps:
1. Login as Admin
2. Open List of Users (https://demo.orocrm.com/desktop/user?grid%5Busers-grid%5D=i%3D1%26p%3D25%26s%255Busername%255D%3D-1%26f%255Benabled%255D%255Bvalue%255D%3D1%26c%3DfirstName1.lastName1.email1.username1.enabled1.auth_status1.createdAt1.updatedAt1.tags1%26v%3Duser.active%26a%3Dgrid%26g%255BoriginalRoute%255D%3Doro_user_index)
3. Click on the Tags filter
4. Type any value

Filter changes its size.

**Comment by Krushelnitskiy** [comment]
@alex-mak  Thanks for the report! Addressed to platform team for fix

INTERNAL ID: BAP-15480

**Comment by anyt** [comment]
Fixed in https://github.com/oroinc/platform/commit/c673eeb59fbf075d88105de50c897dad5202dd53.

Thank you for contribution!
