### ISSUE TITLE
[ContainerResetExtension] Memory leak in unserialize & gc_collect_cycles taking about 40% of all execution time

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#755]
Hi, 
When we fixed problem `Too many connections error` from ticket https://github.com/oroinc/platform/issues/754 (more easy set in postgresql.conf `max_connections` = 20000). We noticed a serious regress of performance related with `persistent_services` (may be related with `oro_featuretoggle.configuration.provider`). This is due to the fact that the garbage collector can not remove some objects, because the references to these objects exist in some `persistent_services` this leads to serious memory leaks

For test we use STR from issue https://github.com/oroinc/platform/issues/754.
Result testing in **PROD**!!! mode (in dev exist leak related with logs handler processors)

| Number of messages processed since last restart MQ   | Speed. message per sec.  | Memory usage MB | GC time to total time |Profiler|
| ------------- |:-------------:| -----:|------:|:-----:|
| 10    | 10.2 | 69.4| < 1% | [blackfire](https://blackfire.io/profiles/0be1fdbe-cabc-4520-8b2b-afdacb0951d6/graph)|
| 100   | 8.8 |   128 | 9% | [blackfire](https://blackfire.io/profiles/75502cf0-a31d-404b-9eb4-c1d72ac4acf6/graph)|
| 1000 | 4.7 |  701 | 39% | [blackfire](https://blackfire.io/profiles/8b8294fc-f521-44c9-9bf5-b178391af2a5/graph) |

On next plot shows depends speed MQ (message per sec.) on number of messages processed since last restart MQ 
![selection_198](https://user-images.githubusercontent.com/21358010/30782615-23740dc4-a13e-11e7-95d1-2527d27312a6.png)

*CRE* - ContainerResetExtension

Memory leak in MQ 
![selection_199](https://user-images.githubusercontent.com/21358010/30782638-817d98e0-a13e-11e7-98a9-2c5a91165277.png)

As you see memory leak do not occur if remove from app.yml all `persistent_services` or disable `ContainerResetExtension`

![selection_200](https://user-images.githubusercontent.com/21358010/30782659-061f86a8-a13f-11e7-9784-3b40c6f34936.png)

**Comment by inri13666** [comment]
Thank you for reporting the issue!

INTERNAL ID: BAP-15540

**Comment by vsoroka** [comment]
fixed in https://github.com/oroinc/platform/commit/2e716817997601c065199e3fcf226a12e3b02d4b
