### ISSUE TITLE
using theme for custom application

### ISSUE THREAD

**Issue by aliasdoc** [oroinc/platform#759]
Hi,

It's not an issue, just a question.

I really like this theme and want to use it in my application to make a small admin backend. Is there a simple way to reuse css and javascript ??
My backend is made with angular4 and i just need css and base ui javascript.

Thank you.

**Comment by NiMias** [comment]
Hi, @aliasdoc !

No, at the moment there is no simple way.

About theming in Oro applications you can read in documentation: https://www.orocrm.com/documentation/2.3/book/layout, 
https://github.com/oroinc/platform/tree/master/src/Oro/Bundle/LayoutBundle.

Best reagrds.

**Comment by aliasdoc** [comment]
Hi @NiMias ,

Thank you for your reply.
