### ISSUE TITLE
run oro:cron:... 

### ISSUE THREAD

**Issue by vafabandi** [oroinc/platform#769]
hi everyone,
I wrote a command and named it oro:cron:oro-cron-test
and it implements CronCommandInterface.
when i run this command " php app/console oro:cron:definitions:load " . 
my command is added to schedule.
after running oro:cron the below message is previewed:
"Scheduling run for command oro:cron:oro-cron-test"
but the command has not been executed. 

I would love a response and I am waiting for one.
thanks in advance

**Comment by yurio** [comment]
Hi, @vafabandi.
To run cron commands you should have a message queue consumer executed with app/console oro:message-queue:consume command.

**Comment by vafabandi** [comment]
hi, @yurio 
I run  app/console oro:message-queue:consume. but yet my command didnt excute. :(

**Comment by alexandr-parkhomenko** [comment]
Hello, @vafabandi .

Try to make your command "synchronous" by adding interface `SynchronousCommandInterface` to it. It will force `oro:cron` omit MQ and run right away the command. Pay attention that your command will be executed in parallel process, so you wont see any output from it within output of command `oro:cron`.

**Comment by alexandr-parkhomenko** [comment]
Hello, @vafabandi.

Please add verbosity level to command `app/console oro:message-queue:consume` by adding parameter '-vv' . It gives you possibility to see what message in process now. Please pay attention that you can have a lot of message already queue, so it can takes some time before your command will be processed. You can check that you message was added to queue by filtering column `body` in table `oro_message_queue` with 'Like %oro:cron:oro-cron-test%'  (Works in case if you use dbal as message queue transport ).

**Comment by manowark** [comment]
Hello, @vafabandi.
Please, provide value that your command will return by `getDefaultDefinition()`. It should be correct cron expression and command will be executed in that time (described by cron expression).

Anyway, I'm now closing this issue as it has been inactive for a while. Please, feel free to reopen it if you have any questions.
