### ISSUE TITLE
Cannot render fields added with migration

### ISSUE THREAD

**Issue by stepansib** [oroinc/platform#774]
Today i updated platform from 1.18 to 2.3.12 and faced strange error (even after fresh app install)

I wrote a migration to add boolean field to User class:

```php
$table = $schema->getTable('oro_user');
        $table->addColumn(
            'with_bonus',
            'boolean',
            [
                'notnull' => false,
                'oro_options' => [
                    'extend' => ['owner' => ExtendScope::OWNER_CUSTOM],
                    'datagrid' => ['is_visible' => DatagridScope::IS_VISIBLE_FALSE],
                    'merge' => ['display' => true],
                    'dataaudit' => ['auditable' => true],
                    'form' => ['type' => 'choice'],
                    'view' => ['is_displayable' => true],
                ],
            ]
        );
```

Migration run successfully but when i try to edit any user i receive following error:

> The option "configs" does not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block", "block_config", "block_name", "by_reference", "cascade_validation", "check_similar_values", "choice_attr", "choice_label", "choice_list", "choice_loader", "choice_name", "choice_translation_domain", "choice_value", "choices" ...

**Comment by stepansib** [comment]
But when i add "string" column with migration - everything works ok.
Looks like this issue happens only with "boolean" columns

**Comment by stepansib** [comment]
Solved with proper `form_type`:
```php
     'form_type' => 'checkbox',
```

**Comment by manowark** [comment]
Hi, @stepansib.

I'm now closing this issue as it seems there are no additional questions about this issue. Please, feel free to reopen it if you have any questions.
