### ISSUE TITLE
mcrypt is deprecated from php 7.1

### ISSUE THREAD

**Issue by slimus** [oroinc/platform#777]
And removed in php 7.2 (https://wiki.php.net/rfc/mcrypt-viking-funeral)

Do you have plan to move to OpenSSL?

**Comment by NiMias** [comment]
Hello, @slimus .

Thank you for the question.

As reveals the investigation (done in task OIS-104):
> mcrypt functionality not used in Oro code. The only thing is that we have incorrectly named class and service within Security bundle Oro\Bundle\SecurityBundle\Encoder\Mcrypt which in fact uses openssl

To solve this confusion has been created the improvement task BAP-16232 (information for the Oro Community support developers).

Thank you one more time for your contribution to the quality of Oro applications!

**Comment by slimus** [comment]
And one small thing: you have requirement from ext-mcrypt (https://github.com/oroinc/platform/blob/master/composer.json#L20)
Thank you!

**Comment by aivus** [comment]
Hi @slimus 
Thank you, we will discuss this with the team.

**Comment by aivus** [comment]
Let's use #782 to track status of `mcrypt` extension.
