### ISSUE TITLE
Behat grid timepicker error.

### ISSUE THREAD

**Issue by xgitxhubx** [oroinc/platform#785]
I have an error when I filter date time element.
Scenario:
```
Scenario: List admin email.
        Given I login as administrator and use in "second_session" as "Manager"
        And I click My Emails in user menu
        And I filter Date Time as between "today" and "tomorrow"
        Then there is no records in grid
```

Error:
`Fatal error: Call to a member function click() on null (Behat\Testwork\Call\Exception\FatalThrowableError)`

I think this line caused issue:
https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/DataGridBundle/Tests/Behat/Element/TimePicker.php#L48

If I move the click action after setting time value, it'll work:
ie:
```
public function setValue($dateTime)
    {
        // $this->click();

        if ($this->hasAttribute('data-validation')) {
            $this->click();
            $timeSelect = $this->getPage()->findVisible('css', '.ui-timepicker-wrapper');
            $time = $this->formatTime($dateTime);

            /** @var NodeElement $li */
            foreach ($timeSelect->findAll('css', 'li') as $li) {
                if ($time == $li->getText()) {
                    $li->mouseOver();
                    $li->click();
                    $mask = $this->getPage()->findVisible('css', '#oro-dropdown-mask');
                    if (!empty($mask)) {
                        $mask->click();
                    }

                    return;
                }
            }

            self::fail(sprintf('Time "%s" not found in select', $time));
        } else {
            parent::setValue(new InputValue(InputMethod::SET, $dateTime->format('g:i')));
            $this->click();
            $this->clickSelectedTime();
        }
    }
```

**Comment by br0ther** [comment]
Hi @dimonixx 
Thank you for reporting the issue!
This issue requires investigation, I will get back to you as soon as possible with the answer. Thank you for your patience!

**Comment by manowark** [comment]
Hello, @xgitxhubx.
I hope it is was fixed in https://github.com/oroinc/platform/commit/027dfec1627adf062a1d9a1cbde65daa70e347c0#diff-5c3deb71125bc3304c005c3f1eee964e.

I just tested your scenario and it is works well.
Now I'm closing this issue as not reproduced. Fell free to reopen it in case if you have additional questions.

**Comment by xgitxhubx** [comment]
Thanks @manowark
