### ISSUE TITLE
[AttachmentBundle] - error on Attachment update

### ISSUE THREAD

**Issue by mechpave** [oroinc/platform#786]
We have a project that is configured to use HTTPS. When we try to update an attachment the widget loads up fine, but after saving it an error is shown that "The widget content loading has failed". Console displays this error: "Blocked loading mixed active content “http://...".

I did not analyze the problem deeper, but looked at the code in `Oro\Bundle\AttachmentBundle\Controller\AttachmentController::updateAction`. Form action is being taken from the request URI: `$formAction = $this->getRequest()->getUri();`. I am suggesting to generate the url manually: `$formAction = $this->generateUrl('oro_attachment_update', ['id' => $attachment->getId()])`.

Would such fix be accepted?

**Comment by bemzaslava** [comment]
Hello, @mechpave.
> Would such fix be accepted?
If it fixes your problem - why not. But in scope of internal issue we will investigate deeper the problem with wrong request schema.

Thank you for your report!
Created an internal task for the problem (id: BAP-16304).

**Comment by SkaiBoa** [comment]
How is going on with this problem? We are stuck in this issue too.

Should we just override the route with the correct line or when this will be fixed ?

**Comment by morozovalexander** [comment]
Cannot confirm this proble. My platfrom version is 2.6 via https
