### ISSUE TITLE
 the patch release for oro platform

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#787]
There is not new maintenance releases since Oct 26 for 2.3, but at the same time in the official site exist information about patch release for EE . You more not support all old versions for oro platform, is it? Will be able security releases for CE?

**Comment by DimaSoroka** [comment]
Hello Volodymyr

Patch releases where we include bug fixes and security fixes for already released minor versions are available for Enterprise customers only with backward compatibility promise, but for CE all fixes typically published in master branch and released in the next minor version release.

**Comment by manowark** [comment]
I'm now closing this issue. Please, feel free to reopen it if you have any questions.
