### ISSUE TITLE
Question: Entity migrations in load balanced environment

### ISSUE THREAD

**Issue by LRotherfield** [oroinc/platform#788]
Hi guys

We are wondering if there is any documentation or if you can tell us the recommended way to run oro platform in a load balanced (multi server) environment? Particularly with regards to the entity system and all of the data it caches in `app/ENV/oro*`.  An example issue would be:

1. In the GUI add a new field to an entity
2. Run the schema update from the GUI
3. Oro now generates the new cache files on the server the command was run from
4. All other servers now have out of date caches and will start to error.

We could mount the cache directory so that it is shared between all servers but that would introduce an NFS overhead on every cache query so that does not seem optimal.

How do you recomend tackling this problem?

Kind Regards  
Luke

**Comment by DimaSoroka** [comment]
Hi @LRotherfield 

Please take a look here: https://oroinc.com/doc/orocrm/current/dev-guide/scale-nodes

**Comment by LRotherfield** [comment]
Great, thanks @DimaSoroka

**Comment by LRotherfield** [comment]
@DimaSoroka have you run into an issue running oro:platform:update with all of the suggested redis caches in place?

Currently I can run all of the commands in update individually and they work fine, but when they are run by the update command I get the following error: 
`You have requested a non-existent service "snc_redis.cache".`

I can see with Xdebug that when this error is thrown, `snc_redis.cache` is still an aliasDefinition and has not been resolved so `getDefinition('snc_redis.cache')` fails during the PHPDumper dump command for the container.

Any thoughts?

**Comment by LRotherfield** [comment]
Never mind, looks like with the newer versions of the platform you have already included snc redis with some configuration so my bundle that also includes it was causing a conflict.  Will leave these comments incase they are helpful to someone else.  

Essentially I just needed to stop including the snc redis extension in my own code

**Comment by LRotherfield** [comment]
@DimaSoroka this is a phpredis issue I think.

With predis, snc_redis.cache will always be a concrete service: https://github.com/snc/SncRedisBundle/blob/1.1/DependencyInjection/SncRedisExtension.php#L189

However, with phpredis `snc_redis.cache` is only created as a concrete definition if logging is set to true on the client (which by default depends on kernel.debug being true): https://github.com/snc/SncRedisBundle/blob/1.1/DependencyInjection/SncRedisExtension.php#L259

Since my project uses phpredis it is failing in production unless I force logging to be on.  Was this one of the reasons you chose predis?

**Comment by LRotherfield** [comment]
@DimaSoroka I think the documentation is pretty out of date https://oroinc.com/doc/orocrm/current/dev-guide/scale-nodes

All of the redis service configuration is done in 2.4+ (or earlier I have not checked) by the RedisConfigBundle.  I only mention this as I followed several steps of the docs and ran into a bunch of errors before reading through the RedisConfigBundle and realising I really had to do nothing.

After some reading through the code, the only thing I really need to do is add 3 valid dsn parameters: https://github.com/oroinc/redis-config#configure-application
And then the bundle will do the rest for me https://github.com/oroinc/redis-config/blob/master/DependencyInjection/OroRedisConfigExtension.php#L107

**Comment by sergeyz** [comment]
Hi, @LRotherfield!

Let's reopen this issue and address it to support team, closed issues will not be processed even with @DimaSoroka 's help

**Comment by NiMias** [comment]
Hello, @LRotherfield!

Thank you for reporting this documentation issue. We are working on the documentation update. (Internal task ID for Oro team members: DOC-672)

**Comment by manowark** [comment]
Confirm that redis works with default configuration, `oro/redis-config` package and parameters in `parameters.yml`:
```
    session_handler: snc_redis.session.handler
    redis_dsn_session: 'redis://127.0.0.1:6379/0'
    redis_dsn_cache: 'redis://127.0.0.1:6379/1'
    redis_dsn_doctrine: 'redis://127.0.0.1:6379/2'
```

**Comment by LRotherfield** [comment]
Yeah, that is my experience too.

Will you plan to support phpredis as an option in the future?

**Comment by manowark** [comment]
Sorry, but I don't know plans for implementation of support phpredis. I will mark this issue 'open for contribution'. Thanks!

**Comment by anyt** [comment]
The documentation issue is already fixed. Thank you!
