### ISSUE TITLE
Upgrade to PHP 7.2.x

### ISSUE THREAD

**Issue by pedrofurtado** [oroinc/platform#795]
There is a plan to make OroPlatform (and OroCRM) compatible with PHP 7.2.x? Because the composer.json dependency of PHP is set to 7.1.x.

**Comment by mbessolov** [comment]
Yes, PHP 7.2 support will be added by the time that PHP team stops maintaining 7.1  (December 2018, according to the list of the Supported Versions at http://php.net/supported-versions.php )

**Comment by pedrofurtado** [comment]
Thanks for feedback, @mbessolov !

**Comment by gplanchat** [comment]
@mbessolov is there a plan to support both PHP 7.1 and PHP 7.2 ? by the fall of 2018, PHP 7.3 will be released.

**Comment by ibasaw** [comment]
+1

**Comment by mbessolov** [comment]
We are working on it.
138 hours, 173 files changed, 3994 insertions(+), 3097 deletions(-)
Not done yet.

**Comment by pedrofurtado** [comment]
Is better to keep this issue open until the release of the version with this compatibility?

**Comment by mbessolov** [comment]
@pedrofurtado we normally close the questions once they are answered. Feel free to reopen if you want.

**Comment by chrisleup** [comment]
What's the PHP 7.3 support looking like these days?
