### ISSUE TITLE
Export error: "Backend header doesn't contain fields"

### ISSUE THREAD

**Issue by simoncarre** [oroinc/platform#799]
Hi everybody!

First of all thank you for your tool. OroPlatform is really a good tool!
I just migrated from version 2.0 to version 2.5 to fix an issue with email templates. It's now fixed!

But I now have another issue with the export of my entities. Some entities export without issues but other entites generate this error: `batch.ERROR: Encountered an error executing the step: Backend header doesn't contain fields`.

Entity configuration looks good and I reset it with the commands:
`php app/console oro:entity-config:cache:clear --env=dev`
`php app/console oro:entity-config:update --force --env=dev`

But nothing better... It looks like there is a kind of cache at the field level. Do you have an idea?

Thank you in advance!

**Comment by d-beekeeper** [comment]
Hi simoncarre!

Try to delete all files\folders from folder 'app/cache' manually, then execute command 'php app/console cache:clear' and then re-check.

If this error persists - please give us a detailed steps to reproduce this error -we will fix it as quick as possible.
Thanks!

**Comment by simoncarre** [comment]
Thank you! It's ok now.
