### ISSUE TITLE
How to add a link in PinTabs List programatically?

### ISSUE THREAD

**Issue by pedrofurtado** [oroinc/platform#802]
![capturar](https://user-images.githubusercontent.com/10530520/35692138-aa5ad3fc-0761-11e8-879e-c44000e77c95.PNG)

How I add a link programatically (with PHP code, inside on my bundle) on PinTabs List in OroCRM?

I'm using OroCRM 2.5.0

**Comment by yurio** [comment]
Hello, @pedrofurtado 

Use pin icon on the right top corner of page to create fast access link in the pinbar.

![pinbar-location](https://user-images.githubusercontent.com/1615700/35694928-8ecb8436-078b-11e8-9cb6-865fd4823510.jpg)

**Comment by pedrofurtado** [comment]
Any news about this issue?

**Comment by pedrofurtado** [comment]
From URL: https://community.oroinc.com/forum/orocrm/orocrm-programming-questions/topic/how-to-add-a-link-in-pintabs-list-programatically/
