### ISSUE TITLE
Proxy organization causing logout on exception

### ISSUE THREAD

**Issue by LRotherfield** [oroinc/platform#803]
Hi guys

We have noticed that during some exceptions we are getting logged out of the system rather than a 500 error page being thrown.

After tracing it through, it seems that the `Oro\Bundle\SecurityBundle\Http\Firewall\ContextListener` will remove the auth token from the session if the user does not have access to the current organization.  That makes sense but in our case the organizations loaded for a user can contain Doctrine proxy objects so although the user has access to an organization, the comparison of the proxy and regular organization object fails and so the user is logged out.

Is it possible with your code that an organization could ever be a doctrine proxy object and cause this issue in the code below?:
https://github.com/oroinc/platform/blob/71bdab4c7cd45c490c3f9b73b5adadbbd95bcf4e/src/Oro/Bundle/SecurityBundle/Http/Firewall/ContextListener.php#L47

If so, would simple fix would be to loop over the organizations and compare their id's?

Cheers
Luke

**Comment by d-beekeeper** [comment]
Thanks for notice LRotherfield 
You are right. Current approach will lead to incorrect behavior in case, if we use Doctrine`s proxy classes.
I created an internal ticket for this issue - so it will be fixed in some future release.

Internal ticket ID: BAP-16495

**Comment by flochntrl** [comment]
Any news ?

**Comment by aivus** [comment]
Hey @flochntrl 
This issue has been fixed in https://github.com/oroinc/platform/commit/d4a2acda4a6cf6a0fa0151cc57d92cb5d988171f

Versions 2.6.38 and >=3.0 contain this fix.

**Comment by flochntrl** [comment]
Thanks @aivus. We are in 2.6.36. We will upgrade

**Comment by aivus** [comment]
Let us know if you still have this issue.
