### ISSUE TITLE
How I override 'OroContactBundle:Contact:view.html.twig' without rewrite code?

### ISSUE THREAD

**Issue by pedrofurtado** [oroinc/platform#804]
I want to override the default “/contact/view/{id}” twig file, located in “https://github.com/oroinc/crm/blob/2.5.0/src/Oro/Bundle/ContactBundle/Resources/views/Contact/view.html.twig”. For that, I’ve created my custom bundle and It is working. But I would extend this twig file in a more elegant way.

One possibility to override this twig file is copy and paste all code inside the file above and change what I need. But there is a way to redefine some blocks of it without need to copy and paste all the code from the original file?

**Comment by pedrofurtado** [comment]
From URL: https://community.oroinc.com/forum/orocrm/topic/how-i-override-orocontactbundlecontactview.html.twig-without-rewrite-code/#post-33907

**Comment by aalgogiver** [comment]
Hi, @pedrofurtado.
As symfony supports of overriding and extending the same template [starting from version 3.4](https://symfony.com/blog/new-in-symfony-3-4-improved-the-overriding-of-templates) this feature will be available in the future releases of the platform.
As an alternative consider to use [scroll data customizations](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/UIBundle/Resources/doc/reference/scroll-data-customization.md).
Here's an [example of this approach](https://github.com/oroinc/orocommerce-orocrm/blob/master/src/Oro/Bridge/CustomerAccount/EventListener/AccountViewListener.php#L74).

**Comment by pedrofurtado** [comment]
Thanks, man! It is solved here. Great links!
