### ISSUE TITLE
Update the repository name of Guzzle library in composer.json

### ISSUE THREAD

**Issue by pedrofurtado** [oroinc/platform#809]
When installing OroPlatform version 2.6.1, the warning message below appears:

![capturar](https://user-images.githubusercontent.com/10530520/36042777-1854e48a-0db4-11e8-80f2-bad1cc0f5094.PNG)

In the "guzzle/guzzle" packagist page, it also have this warning message ("This package is abandoned and no longer maintained. The author suggests using the guzzlehttp/guzzle package instead."). 
See -> https://packagist.org/packages/guzzle/guzzle

**Comment by bemzaslava** [comment]
Hello, @pedrofurtado and thank you for reporting the issue!

Yes, it is a known problem, see https://github.com/oroinc/orocommerce/issues/20
And we already created an internal issue for fix. (internal ID: BAP-15118)

**Comment by manowark** [comment]
I am now closing this issue as it is duplicate. Please, feel free to reopen it if you have any questions.
