### ISSUE TITLE
PageComponents can not be initialized for the element without own layout after after platform update from 2.3.0 to v2.6.1

### ISSUE THREAD

**Issue by NikDevPHP** [oroinc/platform#812]
Hi, we updated to version 2.6.1 and we had the following errors in chrome console:

![oro_errors](https://user-images.githubusercontent.com/11384994/36380424-482220b0-1593-11e8-904e-b3aa84cb5ff3.png)
It's not entirely clear why this is due to shortcuts-view.js. We don't use the shortcuts template and it's disabled for us in config.yml oro_ui settings:

        navbar:
            items:
                shortcuts:
                    remove: true
                search:
                    remove: true

Have an idea why this can happen?

**Comment by Grygir** [comment]
Hello @NikDevPHP ,

Thank you for reporting the issue. JS-code that initializes `ShortcutsView` does not take in account that shortcuts placeholder can be removed. We will try to fix it in the upcoming patch release. 

But I see that you have the same issue with `PageBeforeContentAdditionView`.It does not have own layout as well. This container is required and cannot be removed as placeholder
https://github.com/oroinc/platform/blob/2.6/src/Oro/Bundle/UIBundle/Resources/views/Default/index.html.twig#L121-L123

**Comment by NikDevPHP** [comment]
Hi, thanks for response.
Yes, with `PageBeforeContentAdditionView` we also have problems. It seems that we should be able to remove `pin button` section as `shortcuts` section and accordingly part of the js code should also be disabled. What do you think about it ?

**Comment by Grygir** [comment]
To remove pin buttons, you can use same approach as you did with shortcuts
```yml
        pin_button:
            items:
                pin_button:
                    remove: true
```

**Comment by anyt** [comment]
Fix already in `master` branch. Will be available in next minor release for Community Edition (3.0.0-rc) and in next patch releases for Enterprise Edition.
https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/UIBundle/Resources/public/js/app/controllers/base/controller.js

Thank you.
