### ISSUE TITLE
The notes and calls not render html tags since oroPlatform  2.6.6

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#820]
Hi, guys
The macros `renderSwitchableHtmlProperty` escape all html tags after update OroPlatform to 2.6.6,  so notes not render as html 

![selection_278](https://user-images.githubusercontent.com/21358010/37346714-1cbb1a76-26e1-11e8-9640-89f0b3d2cc17.png)

![selection_279](https://user-images.githubusercontent.com/21358010/37346712-1a46d6ae-26e1-11e8-9db6-fa410212a76f.png)

**Comment by yurio** [comment]
Hello, @vtsykun.
Thank you for reporting the issue!
Created an issue to fix (Internal ID - BAP-16755)

**Comment by anyt** [comment]
Fix merged to master https://github.com/oroinc/platform/commit/f4dc13c0b5407cd95043b597b4002622417c1c79
