### ISSUE TITLE
Bug:  Cannot save Multi-Select fields

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#829]
Hi Oro Team,

Tested on 2.3, 2.6, and 3.0 (demo.orocrm.com)

In the datagrid, there is no longer a way to save or undo changes of multi-Select fields.
![image](https://user-images.githubusercontent.com/794449/38473778-486e1466-3b63-11e8-8be0-d8e3f4d10c8b.png)

Currently, the only way to save changes to a multi-select field is to click on the edit button of another field.

# How to reproduce

1. Add a multi-select field
2. update shema
3. Go to the datagrid and click Edit.
4. Pick new values
5.  Try to save .....

![oro-platform-multiselect-save](https://user-images.githubusercontent.com/794449/38473776-4199fd6c-3b63-11e8-9cb1-626ce3952247.gif)

# Side note / Related other bug
Navigating  datagrid fields with  ALT+ARROW KEYS stop working when you reach a multi-Select field

Have a good day,
Samuel

**Comment by Grygir** [comment]
Hello @sadortun 
Thank you for the bug report. Have created internal ticket BAP-16877

**Comment by sadortun** [comment]
ping @dmitrosh

**Comment by anyt** [comment]
The fix merged to master, already released at `3.0.0`, `2.6.15`, `2.3.33`.

Thank you for contribution!
