### ISSUE TITLE
Error in --env=prod oro:cron -vvv, after disabled the Consumer Heartbeat functionality

### ISSUE THREAD

**Issue by SkvokeN** [oroinc/platform#837]
Hi, 
After set the `heartbeat_update_period` option to 0, `--env=prod oro:cron -vvv` command doesn't work.
In `oro_cron_schedule` table, we have record 
`2	oro:cron:message-queue:consumer_heartbeat_check	[] 751713988987e9331980363e24189c */0 * * * * `
An error occurs in your dependency, when it trying to parse `*/0 * * * *`. 

Link to error:
https://cdn1.savepice.ru/uploads/2018/4/27/cffa92682f496b86c25661d66fbc21d1-full.png

**Comment by anyt** [comment]
Hi @SkvokeN,

Thank you for reporting the issue! We greatly appreciate all contributions to Oro projects.

Internal issue id #BAP-16992

**Comment by anyt** [comment]
Fixed in 4.1.1
