### ISSUE TITLE
3.0 RC Token Storage Decorator Bug

### ISSUE THREAD

**Issue by LRotherfield** [oroinc/platform#846]
I have just been trying to get a new version of Oro installed using version 3.0rc.  The installation is completely new using the platform application repository and after installation I am getting the following error:

> Type error: Argument 1 passed to Symfony\Component\Security\Http\Logout\CsrfTokenClearingLogoutHandler::__construct() must implement interface Symfony\Component\Security\Csrf\TokenStorage\ClearableTokenStorageInterface, instance of Oro\Bundle\EmbeddedFormBundle\Manager\CsrfTokenStorageDecorator given

Updating `Oro\Bundle\EmbeddedFormBundle\Manager\CsrfTokenStorageDecorator` to implement `Symfony\Component\Security\Csrf\TokenStorage\ClearableTokenStorageInterface` fixes the problem but obviously requires a clear function to be implemented.

**Comment by anyt** [comment]
this is known issue introduced by Symfony in patch update, please use `3.0.0-rc` tag where we locked Symfony version to 3.4.9 instead.

**Comment by LRotherfield** [comment]
Ahh thanks
