### ISSUE TITLE
Cannot enable comments for my custom Entity with too long name

### ISSUE THREAD

**Issue by morozovalexander** [oroinc/platform#849]
I have a custom Entity named “PriceRequestHistory” and I need to enable comments for it.
My migrations for it was writen like in [this](https://github.com/oroinc/platform/tree/master/src/Oro/Bundle/CommentBundle) tutorial.

1. My migrations failed with an error

“ERROR: Max column name length is 30. Please correct “oro_comment:price_request_history_b954e5f7_id” column in “Dwdm\Bundle\PriceBundle\Migrations\Schema\v1_4\DwdmPriceBundle” migration”.

So the length of autogenerated field “price_request_history_b954e5f7_id” is too long.
2. When I tried to use ExtendExtension->addManyToOneRelation(…) and use my custom “$targetTitleColumnName” argument with shorter name “dwdm_p_r_h” the ActivityListMigration probably generates wrong relation name “$price_request_history_b954e5f7” in EX_OroCommentBundle_Comment entity.
3. I tried to rename my class with file, but I’ve got too mush errors and problems with classnames stored in database.

So what can I do with too long autogenerated field names? My oro platfrom version is 2.2.*. Thank you.

**Comment by morozovalexander** [comment]
this problem still actual in 2.6 platform version

**Comment by easybi-ts** [comment]
I have the same problem

**Comment by anyt** [comment]
Hi @easybi-ts,
What version of an application do you use? It's not the issue any more in the current LTS, 4.1, as I know.

**Comment by easybi-ts** [comment]
php bin/console oro:package:installed  

           akeneo/batch-bundle : 0.4.11
             oro/oauth2-server :  4.1.3
                  oro/platform :  4.1.6
oro/platform-serialised-fields :  4.1.2
              oro/redis-config :  4.1.2
            oro/twig-inspector :  1.0.3

The problem is in vendor/oro/platform/src/Oro/Bundle/MigrationBundle/Tools/DbIdentifierNameGenerator.php  
As far as I can see this is not solved even in alfa branches, the value 30 is hardcoded.

**Comment by anyt** [comment]
I see what you mean. In OroPlatform there is a limitation to the table and column name length to 63 characters. It's dictated by Postgres support, Mysql has the limit to 64 characters. 

In the older application versions, we had a limit to 30 characters, that's why all the generators are stick to this number and we can't update it without breaking the upgrade process for existing applications.

You can provide a custom DbIdentifierNameGenerator that will decorate the original one to provide a custom name for some specific columns or you can change the strategy for the whole application, but it might break some migrations in core or extensions where people hardcoded relation names.

**Comment by easybi-ts** [comment]
I have created a decorator, but there is a problem:  
`In OroEntityExtendBundle.php line 121:
                                                                               
  Symfony\Component\Debug\Exception\FatalThrowableError {#5                    
    -originalClassName: "TypeError"                                            
    #message: "Argument 3 passed to Oro\Bundle\EntityExtendBundle\Tools\Exten  
  dConfigDumper::__construct() must be an instance of Oro\Bundle\EntityExtend  
  Bundle\Tools\ExtendDbIdentifierNameGenerator, instance of Easybi\Bundle\One  
  DSBundle\Service\DbIdentifierNameGeneratorDecorator given, called in /var/w  
  ww/easybi/easybi/var/cache/dev/ContainerW1AY2CT/getOroEntityExtend_Tools_Du  
  mperService.php on line 23"                                                  
    #code: 0                                                                   
    #file: "./vendor/oro/platform/src/Oro/Bundle/EntityExtendBundle/Tools/Ext  
  endConfigDumper.php"                                                         
    #line: 66                                                                  
    #severity: E_RECOVERABLE_ERROR                                             
    trace: {                                                                   
      ./vendor/oro/platform/src/Oro/Bundle/EntityExtendBundle/Tools/ExtendCon  
  figDumper.php:66 { …}                                                        
      ./var/cache/dev/ContainerW1AY2CT/getOroEntityExtend_Tools_DumperService  
  .php:23 {                                                                    
        require                                                                
        ›     yield 8 => ($this->privates['oro_entity_extend.entity_config_du  
  mper.extension.index'] ?? $this->load('getOroEntityExtend_EntityConfigDumpe  
  r_Extension_IndexService.php'));                                             
        › }, 9));                                                              
        ›                                                                      
        arguments: {                                                           
          $entityManagerBag: Oro\Bundle\EntityConfigBundle\Config\EntityManag  
  erBag {#173 …}                                                          `

My services.yml:  

`services:
    _defaults:
        public: true

    ebi_oneds.service.db_id_name_generator_decorator:
        class: Easybi\Bundle\OneDSBundle\Service\DbIdentifierNameGeneratorDecorator
        decorates: oro_migration.db_id_name_generator
        decoration_priority: 1000
        arguments:
`

I do not know why my decorator replaces Oro\Bundle\EntityExtendBundle\Tools\ExtendDbIdentifierNameGenerator, this isn't even the same bundle.

**Comment by easybi-ts** [comment]
Seems to work now :)  

However it would be very nice if we could overwrite such values in parameters.

**Comment by anyt** [comment]
For now, I mark this issue as closed, as initially, it was a question, and we are not going to change the name limit to support BC promise. 
However, if someone willing to contribute the solution that will save BC and allow greater length for new fields, feel free to create a PR. We highly appreciate all the contributions.
