### ISSUE TITLE
Agressive REINDEX on every platform update

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#863]
Hi Oro Team,

CC @manowark  @d-beekeeper 

I am not sure if this is the intended functionality, since https://github.com/oroinc/platform/commit/09e216c5ec939742f7c0f0cfb51b83d7d696a559,  every `oro:platform:update` trigger a full `search:reindex` on the database.

If the reindex was scheduled, that would not be an issue, but currently,  platform:update timeout after 300 seconds.

> The process "'/usr/local/bin/php' 'app/console' 'oro:search:reindex' '--env=prod'" exceeded the timeout of 300 seconds.

Is it normal that a full reindex is performed on every platform:update ?

----
Quick numbers: I let the reindex run for an hour, and it it's still in progress. ....  Running it `--scheduled` generate about 1000 jobs :)

Thanks,
Samuel

**Comment by anyt** [comment]
The command isn't smart to know what is really required.
So by default it triggers everything that can be necessary.
But there are several options to disable optional things manually and search reindex is one of that long running thing that be disabled on platform update. Just run the command with ’-h’ option to know what you can skip.

**Comment by anyt** [comment]
This is only the default behaviour, that will work for applications with small amount of data without any issues. But you can control when to run reindexation and weather to make it scheduled manually during platform update.
Here is the note from the [documentation](https://oroinc.com/orocrm/doc/current/dev-guide/cookbook/how-to-upgrade-to-new-version)
> To speed up the update process, consider using –schedule-search-reindexation or –skip-search-reindexation option:
`–schedule-search-reindexation` — postpone search reindexation process until the message queue consumer is started (on step 9 below).
`–skip-search-reindexation` — skip search reindexation. Later, you can start it manually using the oro:search:reindex and oro:website-search:reindex commands. See Search Index: Indexation Process.

**Comment by sadortun** [comment]
Awseome, thanks for the link to the docs.
