### ISSUE TITLE
"Could not load type "choice": class does not exist."

### ISSUE THREAD

**Issue by Briones** [oroinc/platform#865]
I'm trying to update a 2.3 version of Oro CRM to a 3.0 version, everything was well, the update command works after some fixes in the code but I come with a new error that I can't figure it out.

When I'm trying to edit a case, It throws the following error: 

`Uncaught PHP Exception Symfony\Component\Form\Exception\InvalidArgumentException: "Could not load type "choice": class does not exist." at /application/vendor/symfony/symfony/src/Symfony/Component/Form/FormRegistry.php line 86`

So I debuggued to know which field was the problem and it is one that I created in a old migration like this: 

```php 
$table->addColumn(
            'storeId',
            'string',
            [
                'oro_options' => [
                    'extend' => [
                        'is_extend' => true,
                        'owner' => ExtendScope::OWNER_CUSTOM,
                    ],
                    'datagrid' => [
                        'is_visible' => false,
                    ],
                    'form' => [
                        'is_enabled' => true,
                        'form_type' => 'choice',
                        'form_options' => [
                            'choices' => StoreInformation::CODES,
                        ],
                    ],
                    'view' => [
                        'is_displayable' => true,
                    ],
                    'search' => [
                        'searchable' => true,
                    ],
                ],
            ]
        );
```

I tried to change the form_type for "ChoiceType::class" using the class `Symfony\Component\Form\Extension\Core\Type\ChoiceType` since the aliases was deprecated in Symfony 2.8 and removed in Symfony 3.0 (https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form)   but that doesn't worked , I assumed that is because is no taking the information for the migration anymore, so I debuggued and I realize that is comming from the `oro_entity_config_field` table in the `storeId` field, I decoded the base64 data and I see this:

`//a:11:{s:6:"entity";a:3:{s:5:"label";s:34:"oro.case.caseentity.store_id.label";s:11:"description";s:40:"oro.case.caseentity.store_id.description";s:19:"contact_information";N;}s:6:"extend";a:7:{s:5:"owner";s:6:"Custom";s:5:"state";s:6:"Active";s:9:"is_extend";b:1;s:6:"length";s:3:"255";s:10:"is_deleted";b:0;s:6:"origin";s:6:"System";s:13:"is_serialized";b:0;}s:4:"form";a:3:{s:10:"is_enabled";i:1;s:9:"form_type";s:6:"choice";s:12:"form_options";a:1:{s:7:"choices";a:8:{s:2:"ar";s:2:"ar";s:2:"cl";s:2:"cl";s:2:"co";s:2:"co";s:2:"ec";s:2:"ec";s:2:"mx";s:2:"mx";s:2:"pa";s:2:"pa";s:2:"pe";s:2:"pe";s:2:"ve";s:2:"ve";}}}s:9:"dataaudit";a:1:{s:9:"auditable";i:1;}s:5:"email";a:1:{s:21:"available_in_template";i:1;}s:8:"datagrid";a:3:{s:10:"is_visible";i:0;s:11:"show_filter";i:0;s:5:"order";N;}s:4:"view";a:2:{s:14:"is_displayable";i:1;s:8:"priority";N;}s:9:"attribute";a:7:{s:12:"is_attribute";b:0;s:9:"is_system";b:0;s:10:"searchable";b:0;s:10:"filterable";b:0;s:8:"sortable";b:0;s:7:"enabled";b:0;s:7:"visible";b:1;}s:6:"search";a:2:{s:10:"searchable";i:1;s:11:"title_field";i:0;}s:5:"merge";a:1:{s:10:"autoescape";b:1;}s:12:"importexport";a:4:{s:6:"header";N;s:5:"order";N;s:8:"identity";i:0;s:8:"excluded";i:0;}}
`

As you can see the form_type is `choice`, and I can't find the way to change that value in the `oro_entity_config_field` since that changing the migration or the FormType doesn't work, also I checked your documentation searching for how to do that migration and I notice that you are still using aliases like `string` or `integer`in the examples like this page:

https://oroinc.com/orocrm/doc/current/dev-guide/customization

Any idea how can I change the form_type for all the fields created with old migrations and aliases? 

Hope the issue is clear enough

**Comment by anyt** [comment]
You can use `php vendor/oro/platform/bin/oro-form-alias-checker/oro-form-alias-checker
` command to fix the issue, but it's require to write the custom migration first.
Here is [an example of the migration](https://github.com/oroinc/OroCalendarBundle/blob/master/Migrations/Schema/v1_20/UpdateFormTypeForExtendDescription.php)

**Comment by Briones** [comment]
That solves my problem, thanks @anyt. The good part is that I only had a few cases that needed the migration.
