### ISSUE TITLE
rabbitmq_delayed_message_exchange and x-delayed-message

### ISSUE THREAD

**Issue by Briones** [oroinc/platform#867]
The documentation https://oroinc.com/orocrm/doc/current/admin-guide/op-structure/mq/rabbit-mq#required-plugins is not clear about the rabbitmq_delayed_message_exchange plugin, it just said that is a required plugin, and the instructions to download and enabled it, but if we enter to the plugin [documentation](https://github.com/rabbitmq/rabbitmq-delayed-message-exchange#usage) it said that we need to declare two headers in order to use it `x-delayed-message` and `x-delayed-type`.

So if we add and enable the plugin but without any configuration or without using the headers, is not the plugin useless? I think the documentation should be more clear about the importance of the plugin and how to use it or configure it, if needed.

**Comment by anyt** [comment]
As rabbit-mq support is an enterprise feature, please contact the team using an enterprise customer portal.

We don't provide support of EE features in public channels.
