### ISSUE TITLE
Emails body-sync error

### ISSUE THREAD

**Issue by jneto81** [oroinc/platform#871]
Hello, a have some problems running the email body sync command

Using mysql 5.7.23 and php 7.1.22. and ORO version 3.1.0-beta 

php bin/console oro:cron:email-body-sync -vvv

In ORMException.php line 144:
                                
  [Doctrine\ORM\ORMException]   
  The EntityManager is closed.

**Comment by anyt** [comment]
Hi @jneto81 ,
Do you have some more detailed error log or stack trace? 
This looks like a bug, but without clear steps to reproduce I cannot confirm it.

**Comment by jneto81** [comment]
Sorry, can't replicate for now.

I had lots of problems with the email. Now it looks ok, but i made some "fixes", in the vendors folder.

I think the problem was created by some email sync that die in the process, creating some database inconsistencies.

My 3 queue workers died before i had the problem. And i had the remove some activities on the database because they were breaking the user activities.

**Comment by jneto81** [comment]
I'm closing this issue because it seems fixed with ORO 3.1.9
