### ISSUE TITLE
Datagrid ActionExtension Acl isGranted Always returning false for ownership=organization

### ISSUE THREAD

**Issue by rierajuan** [oroinc/platform#873]
Hi!  when an entity has been configure with ownership organization, and after you make any changes to administrator role and save it. Then at index page of that entity  with datagrid, when ActionExtension is performing Acls chekings if that entity has granted current action it's always returning false and add the row result to array of disableActions [https://github.com/oroinc/platform/blob/100d88796bf995d2fcc4d6609db0a1ae3cd2cfac/src/Oro/Bundle/DataGridBundle/Extension/Action/ActionExtension.php#L176](url)

How to reproduce:
1. Take for example Channel Entity, create a new chanel type with a user with administrator role.
2. You can see at the index page the main grid with all action available after save the new channel type. (edit/view/delete)
3. Go and change any permission in the administrator role and save it. 
4. go back to channels index page and check now no actions is avalible, you can't access from the grid to see or edit the entity anymore.
5. If you want to access for example to view page, you need to do it manually ( domain.com/channel/view/1 )

Check for version  orocrm <= 2.26 and platform <=2.6.34

**Comment by yurio** [comment]
Hi, @rierajuan.

Thanks for reporting this issue. Internal id: BAP-17991.

To hot fix this issue you can override the **service oro_security.owner.decision_maker** with your own class and at tis class you have to override **isAssociatedWithOrganization** function. 

At this method, change the 

`$ownerId = $this->getObjectIdIgnoreNull($this->getOwner($domainObject));`

string to :

`$ownerId = $domainObject instanceof DomainObjectReference ?
            $domainObject->getOwnerId() :
            $this->getObjectIdIgnoreNull($this->getOwner($domainObject));`

**Comment by mbessolov** [comment]
Fixed in db9730894da77f599f45b727ff39e2a3b7da41dc
