### ISSUE TITLE
How your versioning works?

### ISSUE THREAD

**Issue by Briones** [oroinc/platform#876]
Acordding [ to your site](https://oroinc.com/orocrm/doc/2.0/community/release-process#orocrm-versions), you are using semantic versioning what means that your versions are like (MAJOR.MINOR.PATCH), but In my multiples attemps for update I realized that you don't follow that rule, I come across to bundles of oroinc in the version 2.3 that tries to use method or classes that doesn't exist in the 2.3 tags of the oroinc/platform.

For example in this file of the 2.6.1 tag you are adding a new method called `isApplicable` 

https://github.com/oroinc/platform/blob/2.6.1/src/Oro/Bundle/DataGridBundle/Extension/AbstractExtension.php#L32

But you started to use it from the Marketing bundle since the version 2.3.11:

https://github.com/oroinc/OroCRMMarketingBundle/blob/2.3.11/src/Oro/Bundle/MarketingListBundle/Datagrid/Extension/MarketingListExtension.php#L63

So, since oro/crm 2.3.8 requires "oro/marketing": "2.3.*", and "oro/platform": "2.3.*", with composer update the latest versions of the 2.3.* tags will be reached, but since the oro/marketing 2.3.11 is requiring a file that is only in oro/platform 2.6.1 tag the system will break. This is not the only case, the same is happening here:

https://github.com/oroinc/crm/issues/305#issuecomment-444526779

So I would like to understand how your versioning works? How can I be sure that updating to the latest version with supposedly only patches that would not break my entire system for a unfulfilled requirement?

Btw your marketing bundle in the 2.3.11 tag has an oro/platform 2.3.* requirement:

https://github.com/oroinc/OroCRMMarketingBundle/blob/2.3.11/composer.json#L20

So I can't explain why is using a method that is not added until 2.6.1 oro/platform version. Is certanly confusing.

Thanks in advance, I hope the problem is clear.

**Comment by mbessolov** [comment]
Hello Roberto,

It is clear what you described. It is correct that at some point it becomes impossible to retrieve consistent updates to **no longer supported** versions of the community editions of Oro producs with composer. 

The version release cycle for Enterprise and Community editions of Oro products is explained [here](https://oroinc.com/orocrm/doc/current/community/release-process#orocrm-community-edition-releases) and [here](https://oroinc.com/b2b-ecommerce/doc/current/community/release-process#orocommerce-community-edition-releases).

The technical background of this is that once a new LTS version is released, we stop wasting our time and resources on updating composer.json depencies of various packages of the previous community edition versions. Some packages still get updated ocassionally, though the composer.json dependencies  and `composer update` in previous versions is guaranteed to work only in enterprise edition applications. 

The community edition users are advised to update to the new LTS version as soon as it is released to keep getting fixes and security updates. Technically, the code is published, and if someone strongly wants to stay on an older version of the community edition and still get new updates of those old packages that are updated - with some additional effort and composer aliasing trickery it should be possible to do that. I would not call it a trivial task though. Everyone can choose what works best for them - not upgrade, or upgrade to next LTS, or do a lot of extra work to apply updated to some old LTS, or receive updates to that old LTS with an enterprise subscription.

**Comment by Briones** [comment]
Hey Michael,

First of all thanks for the quick answer. 

It's more clear for me with your answer what's happening. I know that you encourage to all users to update as soon as possible to the LTS versions, in my case at least is not that we don't want to update is just that we are so behind in the updates that is not an easy path, I tried to update to 3.0 but I realize that for you the 3.0 is a "preview" so is not recommended for production, I also tried to update to 2.6 that is the latest LTS but I get errors about not founding some class from the Magento Bundle (even though I don't use that bundle and I have it excluded), so I thought in update first for the little bugfixing updates and wait for the 3.1 in January hopefuly. 

The part that I don't understand is the way that the team manage it to create an security/bugfixing update for an old version without testing compatibity with the same version packages. In that case doesn't make any sense to even release a bugfixing update. Normally when a company has an Enterprise version and a Community version the Community one is the base for the Enterprise version and they allow to use the version that they want/need, obviously without official support but allowing to do a clean installation of the version that they want. For what I understand with OroCRM that's not the case, so no one can at this moment make a clean installation of a 2.3 version of OroCRM because it will be broken from the beginning. That's just weird.

For example right now I can install an older version of phpunit if I want to and I know that is gonna work becasuse it worked when was released, I know that I'm not gonna get any support for using it but it should work anyway. Otherwise what's the point of using semantic versioning at all if a patch update have breaking changes?

In any case I'm in the limbo right now, I can't update to OroCRM 2.3.12 because is broken from the beginning, I can't update to 2.6.* because it gives me errors of classes not be founded (probably the same case of dependency errors), I can't update to 3.0 because is not production recommended, and I have to wait to 3.1 in January but I don't know if will be possible update from a 2.3 version to a 3.1 version with your upgrade script since seems that the team doesn't invest time in compatibility with oldest versions that the LTS.

Anyway, I don't have a problem to wait to the 3.1 and try it, but I would like to know if will be possible to update from a 2.3 version to a 3.1 version directly? Or what do you recommend in this scenario?

**Comment by mbessolov** [comment]
You can install any version of our application using [our repository](https://github.com/oroinc/crm-application/tree/2.3.12) and the included [composer.lock](https://github.com/oroinc/crm-application/blob/2.3.12/composer.lock) file. That's why composer.lock is there - to make sure that `composer install` works and works fast.

The following correctly installs all dependencies:
```
git clone -b 2.3.12 git@github.com:oroinc/crm-application.git
composer install
```

And speaking from my personal experience trying to upgrade an old version of PHPUnit on one project, with some additional plugins installed with composer - it did not work. I had to disable all plugins and revert to the plain vanilla PHPUnit. On after that was I able to get a fix in the same branch. It's pretty much the same here - you can install any old version of vanilla OroCRM with the provided composer.lock. Once you start managing dependencies on your own with composer - it will work only as long as the version is supported. After the version becomes unsupported - composer update may or may not work.

I do not see any reasons why a direct upgrade from 2.3 LTS to 3.1 LTS would not work. But we do not test upgrades skipping versions of the community edition, so it is not guaranteed.

**Comment by Briones** [comment]
Gonna try that or some workaround based in your composer.lock, thanks again for all the clarification. 

I hope that the update to 3.1 LTS from 2.3 LTS works when it's released 👍.
