### ISSUE TITLE
BUG: Themes generation not working as expected

### ISSUE THREAD

**Issue by abdessamad** [oroinc/platform#891]
Hi,

Demo theme (and custom themes) does not work on a fresh install of OroPlatform 3.1.2.
I just change acive_theme to demo in config.yml.

```
oro_theme:
    active_theme: demo
```
and:
php bin/console oro:install

Thanks

**Comment by abdessamad** [comment]
In fact, during the installation (oro:install) and the update(oro:platform:update), the active theme is not taken on account (as it was before).

I generated the theme manually with:

```
php bin/console assets:install
php bin/console oro: assets: build admin.demo
```

and it works now.

**Comment by anyt** [comment]
Hi @abdessamad ,

There is outdated documentation. 
Thank you for the report, we will update the doc and remove useless config `oro_theme.active_theme`.
You can set an active admin theme in `webpack.config.js` file by calling `.setAdminTheme('admin.demo')`.

**Comment by abdessamad** [comment]
HI @anyt , 
You're welcome!

**Comment by abdessamad** [comment]
It's working now
Thank you.

**Comment by LRotherfield** [comment]
It might be helpful to leave this bug open until a fix is pushed live, I just started making a ticket for it after searching the open issues for `theme`.

**Comment by mbessolov** [comment]
_internal issue ID: BAP-17222_
