### ISSUE TITLE
UI/UX adjustments after apply new styles

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#894]
# 1. Not all grid rows are shown. 
Go to contact page and sort by id. The 50th record is not shown.
![selection_999 133](https://user-images.githubusercontent.com/21358010/53268852-417cd480-36f8-11e9-9712-4e70017469a6.png)

# 2. Broken grid style
**STR**
1) Select all rows on grid
2) Try to sort by any field
Result:
![selection_999 138](https://user-images.githubusercontent.com/21358010/53301939-b02d6f80-3869-11e9-9410-00d19691d23f.png)

# 3. User menu header is not shown in entity view page.
![peek 2019-02-14 02-47](https://user-images.githubusercontent.com/21358010/53269006-c23bd080-36f8-11e9-8294-d7b901d709ce.gif)
Here should be shown header
![selection_999 134](https://user-images.githubusercontent.com/21358010/53269130-22327700-36f9-11e9-8d87-502c0db1c23b.png)

# 4. Two scroll bars on entity view page 
![selection_999 136](https://user-images.githubusercontent.com/21358010/53269328-a422a000-36f9-11e9-8890-be339161eb70.png)
Also, when scrolling by a scrollspy, it hides under the first scroll bar
![peek 2019-02-14 02-40](https://user-images.githubusercontent.com/21358010/53269572-49d60f00-36fa-11e9-8273-6f025e4430f4.gif)

# 5. The other small defects 
![selection_999 137](https://user-images.githubusercontent.com/21358010/53271851-b522df80-3700-11e9-9761-2e611d70dd4a.png)
### img2
![selection_999 097](https://user-images.githubusercontent.com/21358010/53271873-c5d35580-3700-11e9-9795-fec6b2102e3f.png)
### img3
![selection_999 096](https://user-images.githubusercontent.com/21358010/53271883-c966dc80-3700-11e9-8b9d-c13fdc8479b7.png)

### Environment:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.81 Safari/537.36
screens 1920x1080

**Comment by anyt** [comment]
> 1. Not all grid rows are shown.
> 2. Broken grid style

can't reproduce on `master` branch, looks like already fixed.

> 3. User menu header is not shown in entity view page. 

already fixed, will be released in next 3.1 patch release.
> 4. Two scroll bars on entity view page

fixed, testing in progress, will be released soon.
> 5. The other small defects

> img1: 

internal ticket id: BB-16198
> img2: 

internal ticket id: BAP-18399
> img3: 

already fixed, will be released in next 3.1 patch release.

**Comment by vtsykun** [comment]
It was fixed since 3.1.4,
Thank you!
