### ISSUE TITLE
BUG: Display of Google Maps

### ISSUE THREAD

**Issue by abdessamad** [oroinc/platform#895]
Hi @fyrye ,

The issue is still valid for latest version (3.1.3).

Is there any news about it?

_Originally posted by @abdessamad in https://github.com/oroinc/crm/issues/321#issuecomment-467374912_

**Comment by fyrye** [comment]
Hi @abdessamad  I'm awaiting approval for updating to the latest version of ORO to proceed with testing. Once completed I will be sure to update you here.

**Comment by abdessamad** [comment]
Thanks @fyrye

**Comment by fyrye** [comment]
@abdessamad I upgraded to v3.1.6 and seems to be working for me. I am closing my original issue.

**Comment by abdessamad** [comment]
@fyrye it works for me too
Thanks

**Comment by fyrye** [comment]
@abdessamad you should close this issue too if all is working.
