### ISSUE TITLE
where is the code that is responsible for filtering records by organization for frontend.

### ISSUE THREAD

**Issue by videni** [oroinc/platform#914]
oro platform is a multiple organization solution,  for frontend, one organization can't see records from another organization, for the backend, when we call `isGranted('VIEW', $object)`，it might be denied  by organization check, but for frontend, we may not have code check permission,   let's assume a customer try to access product which is not in his organization,    where is the source code for this feature?

**Comment by anyt** [comment]
Hi @videni ,
What do you mean by the `frontend`? we have it in OroCommerce, but not in the plain platform.

> oro platform is a multiple organization solution

Not exactly, oro platform supports only a single organization. To have multiorganization support you have to use an *Enterprise Edition* of OroCrm or OroCommerce.

**Comment by videni** [comment]
@anyt , I mean OroCommerce frontend. I am using Oro technologies to build  a multiple organization based  project, I am not using OroCommerce,  or OroCRM, just some technologies that is useful for my customization.  it seems some code are not open sourced.

1. enable features for specific organization. a organization can only use features he owned. both backend and frontend.

2. and this issue.

3. multiple organization management.

**Comment by mbessolov** [comment]
Organization-specific product features are available only in OroCommerce Enterprise Edition. If you are an Enterprise Edition customer or a partner - please use the support portal to submit your request.
