### ISSUE TITLE
The API is broken: «page[size]» / «The filter is not supported»

### ISSUE THREAD

**Issue by dmitry-fedyuk** [oroinc/platform#918]
![01](https://user-images.githubusercontent.com/83204/57553168-c1c5e400-738f-11e9-8bd8-91abb4b50e48.png)

**Comment by vsoroka** [comment]
It seems that "Content-Type" request header does not equal to "application/vnd.api+json".
Please check it in "Curl Command Line" section or via browser developer tools window.
This header should be added by default to Headers section of the sandbox, please check if it is exist in your sandbox.

**Comment by dmitry-fedyuk** [comment]
Yes, you are right, thanks!
The `Content-Type: application/vnd.api+json` header solves the problem.
The Oro sandbox does not add this header automatically.

**Comment by vsoroka** [comment]
Which version of the Oro Platform do you use?

**Comment by dmitry-fedyuk** [comment]
The latest: 3.1.6.
