### ISSUE TITLE
Segment Filter: Multi-Select "Not any of" not working

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#923]
Hi Oro Team

The multi-select "not any of" filter does not work anymore in 3.1.

How to reproduce

1) I've added an multi-enum field to the Contacts  `testenum`

![image](https://user-images.githubusercontent.com/794449/58430745-a38f0200-8078-11e9-954d-7711ba8171fc.png)

2) I've created a test segment including the field and values to exclude: 
![image](https://user-images.githubusercontent.com/794449/58430794-dcc77200-8078-11e9-884e-669600da5125.png)

3) Results that are displayed are wrong.
```sql
SELECT o0_.id AS id_0, o1_.email AS email_1, o0_.testenum_ss AS testenum_ss_2, o0_.id AS id_3, o0_.organization_id AS sclr_4, o0_.user_owner_id AS sclr_5 
FROM orocrm_contact o0_ 
LEFT JOIN orocrm_contact_email o1_ ON o0_.id = o1_.owner_id AND (o1_.is_primary = true) WHERE o0_.id IN (SELECT o2_.id FROM orocrm_contact o2_ 
LEFT JOIN orocrm_contact_email o3_ ON o2_.id = o3_.owner_id AND (o3_.is_primary = true) WHERE o2_.id IN (SELECT o4_.id FROM orocrm_contact o4_ 
INNER JOIN oro_rel_83dfdfa4bc56bacb3aa86b o6_ ON o4_.id = o6_.contact_id 
INNER JOIN oro_enum_dee077b0_f846c8a o5_ ON o5_.id = o6_.ev_contact_testenum_f846c8a_id WHERE o5_.id IN ('a', 'b', 'c')) AND o2_.organization_id = 1) AND o0_.organization_id = 1 ORDER BY o0_.id ASC LIMIT 25 OFFSET 0
```

Confirmed by the SQL above `WHERE o5_.id IN ('a', 'b', 'c'))`
![image](https://user-images.githubusercontent.com/794449/58430807-f36dc900-8078-11e9-8281-73820d928823.png)

PS: Also tested with TAGS, and Tags `not any of` is _working as expected_

Have a good day,
Samuel

**Comment by sadortun** [comment]
Found the issue !! 💃 
In `vendor/oro/platform/src/Oro/Bundle/FilterBundle/Filter/MultiEnumFilter.php`

![image](https://user-images.githubusercontent.com/794449/58432310-ae996080-807f-11e9-8ec1-2e5d68309e06.png)

The `in_array` use STRICT_TYPE flag, sadly, the `$comparaisonType` is a string, and your `DictionaryFilterType` are `integers`

**Comment by mbessolov** [comment]
_Internal ID: BAP-18936_

**Comment by sadortun** [comment]
@mbessolov I think this was fixed according to the changelog
- Fixed Multi-Select "Not any of" filter in segments works as "any of" filter

**Comment by anyt** [comment]
Thank you for the reminder, @sadortun. Yes, it is fixed!
