### ISSUE TITLE
Querybuilder / Segment SQL Optimisation

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#925]
Hi Oro Team,

We are investigating why on some query the Segment page become very slow ( 30-45 seconds to load with complex query),

# Topic 1 
We found that the filter query is executed twice and the only difference is the `LIMIT` clause. and there is query executed multiple times

 - If you look bellow at query # 57 and query # 59.  Is # 57 nessessary ? If not, this could improve loading time by 25% ! 
- If you look at query # 56 and # 58, they are **identical** .... That would be another 25% improvement in speed.

Optimizing theses two would give users a 50% improvement in all features related to segments ! 

(example with query   `email contains "a"`
![image](https://user-images.githubusercontent.com/794449/58928185-88c72800-871f-11e9-93de-d875fe0e39e7.png)

# Topic 2

In our use case, the COUNT() query takes almost **15 seconds**, compared to the SELECT which takes about **300ms**. 

- Do you have any idea why the COUNT() is taking such excruciating (**50 times**) time to run ?

![image](https://user-images.githubusercontent.com/794449/58929296-54a23600-8724-11e9-85b4-ae15cb030eb3.png)

Have a good day,
Samuel

**Comment by sadortun** [comment]
The query # 57 seems to come from  https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/QueryDesignerBundle/Validator/QueryValidator.php#L105

Is it normal the validation run every time the segment is displayed ?

**Comment by sadortun** [comment]
After some troubleshooting, i've found out that the query are only executed by the validate() method

https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/QueryDesignerBundle/Validator/QueryValidator.php#L100

And results from query # 56 and # 57 are discarded. Then re-executed by the appropriate getGridData()

Is it normal the validation run every time the segment is used ?

**Comment by aivus** [comment]
Hi @sadortun 
Thank you for your investigation

We need some time to check this

**Comment by sadortun** [comment]
Hi @aivus 

Do you have an update on this ? Can you provide an ETA ? It's a blocking issue for us. 

We are willing to pay to get support on this issue quickly if it can help to get a faster resolution.

Thanks,
Samuel

**Comment by anyt** [comment]
Hi @sadortun,
For now, no ETA as it's quite complex and not a high priority issue. Also, I didn't find any similar issue reported by the enterprise customers that are still open, this usually means that the query performance is good enough on a PostgreSQL. And this is actually expected behavior that complex queries are significantly slower on Mysql.

**Comment by sadortun** [comment]
Closing, since TOPIC 1 is covered by #965 and TOPIC 2 is covered by #967
