### ISSUE TITLE
Can't reply an email adding attachments

### ISSUE THREAD

**Issue by Briones** [oroinc/platform#937]
Version affected: 3.1.9 (since this commit: https://github.com/oroinc/platform/commit/fb25a7e6c8667b9351c1781cc5383659fefcb54c#diff-dac1f9ae15157a61706c61bc1ef1bf28) 

Right now is not possible to reply an Email adding attachments into the Cases section of OroCRM system. 

Steps to reproduce:

1. Enter into a case with an Email in the "Activities" section. 
2. Click in the ... dots at the right of the Email.
3. Select "Reply" button and wait to the widget "Send email" to open.
4. In the widget click in the "Upload" link.
5. Select a file to attach.
6. Click in the "Send" button. 

As result the widget seems to send the request but without success and it just reload the widget but now without the attachment, after reload the page no email was sent either. 

I installed a clean version of crm-application 3.1.9 and the issue is happening there also, I tried to track the problem and I realize that is maybe caused by this commit:

https://github.com/oroinc/platform/commit/fb25a7e6c8667b9351c1781cc5383659fefcb54c#diff-dac1f9ae15157a61706c61bc1ef1bf28

Because If I remove the "_widgetInit=1" of the "action" of the Widget Form it works like it should, but that approach breaks the "Send Email" (no reply) widget in the general section.

**Comment by Briones** [comment]
I managed to fix it in my local by overriding the EmailHandler class and doing:

```php
$request->query->remove('_widgetInit');
``` 
Before this line:

https://github.com/oroinc/platform/blob/fb25a7e6c8667b9351c1781cc5383659fefcb54c/src/Oro/Bundle/EmailBundle/Form/Handler/EmailHandler.php#L69

With this change it removes the value of `_widgetInit` from the `GET` parameters and it takes the one in the `POST` parameters. 

But there should be an appropriate solution from Oro side.

I believe that the problem is only happening with Replys with Attachments since the request for Attachments is `multipart/form-data` and it sends the `GET` parameters from the "action" tag of the form along with the `POST` parameters so we will have two `_widgetInit` params with different values, one of the `GET` params and one in the `POST` params. , and when you don't put any attachments the request is `application/x-www-form-urlencoded` that only sends the `POST` parameters.

**Comment by anyt** [comment]
Confirmed the bug. Thank you for the report.
Internal ticket id #BAP-19096

**Comment by Briones** [comment]
Seems that is finally fixed in crm-application 3.1.15 release, thanks!
