### ISSUE TITLE
[DashboardBundle] Add Widget duplicates widgets on subsequent loads

### ISSUE THREAD

**Issue by fyrye** [oroinc/platform#938]
|   Q |    A   |
| --- | --- |
| oro/platform | 3.1.9 |
| php | 7.2.16 x64 NTS |
| server | CentOS 6.10 x64 |
| client | Windows 10 Pro x64 |
| browser | Chrome 75.0.3770.142 |
| Bug | Yes |
| BC Break | No |
| persistence | ~3.1.6 |

**Steps to reproduce:**

From the Dashboard page, when opening and closing the _Add Widget_ modal multiple times, the list of widgets is duplicated for each time the button is clicked, until the Dashboard page is requested again.

**Example:**

![image](https://user-images.githubusercontent.com/302306/61729501-5a3ff380-ad45-11e9-96e1-464832b5b6cd.png)

**Comment by mbessolov** [comment]
@fyrye  thank you for the bug report.
The issue has been fixed and will be published in one of the next patch updates.
(_internal reference - BAP-18522_)
