### ISSUE TITLE
Data lost after saving form with fields protected by ACL 

### ISSUE THREAD

**Issue by vtsykun** [oroinc/platform#939]
STR
1. Enable Field ACL for contact entity
https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/SecurityBundle/Resources/doc/field-acl.md
2. Create user role "Contact manager" that allow edit only email and address field for contact
![Selection_999(359)](https://user-images.githubusercontent.com/21358010/61737349-ab290980-ad90-11e9-826f-d47eb8ebbcf9.png)
Also may be used data fixture to do it. https://gist.github.com/vtsykun/f8a2a3dc441d82eef144c170af4e5460
3. Create a new user for this role
4. Create a new contact under admin user role
![Selection_999(360)](https://user-images.githubusercontent.com/21358010/61737579-2db1c900-ad91-11e9-94c5-47b51619ea6c.png)
5. Login under "Contact manager" role and try to add new address
6. You must see only email, address and phone fields on form
![Selection_999(364)](https://user-images.githubusercontent.com/21358010/61737749-87b28e80-ad91-11e9-89d1-ceb3befd9694.png)
7. Save contact form

After saving the form, data that was not displayed on the form will be lost.
![Selection_999(362)](https://user-images.githubusercontent.com/21358010/61737869-c6e0df80-ad91-11e9-87df-b2be2e9ba225.png)

**Comment by anyt** [comment]
Internal ticket id #BAP-15208

**Comment by anyt** [comment]
Fixed in 4.1.3. Thank you!
