### ISSUE TITLE
Manual segment refresh should be done by oro:message-queue

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#964]
Hi Oro Team,

Since refreshing a manual segment can be a long running task, we think it should be processed by a background task with `oro:message-queue:process`

We already have an implementation ready but we are missing a small key piece. We need to be able to notify the end-user that the message queue has finished. 
How can we send a flashBag notification to the user from the message processor ?

Related forum post :  https://forum.oroinc.com/orocrm/orocrm-how-do-i-questions/topic/send-message-from-message-queue-processor-to-ui

Thanks, 
Samuel

**Comment by RocKordier** [comment]
Hey @sadortun 

The Async DatagridExport sends an email to the user.
https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/ImportExportBundle/Async/Export/PostExportMessageProcessor.php#L137

But maybe it's similar like the `outdated content flash message`?
https://oroinc.com/oroplatform/doc/current/dev-cookbook/websockets/content-outdating-notifications#dev-cookbook-system-websockets-content-outdating-notifications

Eric

**Comment by sadortun** [comment]
Thanks @RocKordier, 

Indeednelwenuse the email example to transmit data from the app to the queue.

For the other direction ( queue to app ), how do you see the usage of the websocket ? We look into it but I dont see how to use that from the message queue.

Thanks,
Samuel

**Comment by anyt** [comment]
Here is an example shared by Mario Prud'homme at the [ORO community slack](https://join.slack.com/t/orocommunity/shared_invite/enQtNTI0MzcyNzA2NjU5LWU4ZTBlNWI2YzA1MzAyMTllNTQ3YzU0ZTIxMzU5NzA4YWFlNmE3Y2EwZTAzZjE5ODE4YjE3NGUwYjUyMWY1ZDI) some time ago:
```php
 $connectionChecker = $this->getContainer()->get('oro_sync.client.connection_checker');
 $websocketClient = $this->getContainer()->get('oro_sync.websocket_client');

 var_dump($connectionChecker->checkConnection());
 var_dump($websocketClient->publish('oro/ping', ['test' => 123]));
```
