### ISSUE TITLE
What the `version` fo DataAuditBundle means?

### ISSUE THREAD

**Issue by Briones** [oroinc/platform#969]
I noticed that in my database in the table `oro_audit` I have a `version` column that has 1 or 2 values in it. I have some registries repeated in all columns except that one has `1` as version and the other has `2` as version.

Nothing in the documentation of DataAuditBundle seems to explain why there is a version field, it should be 1 or 2 for all of them? 

I would like to know if I can remove all the version `1` records for those cases that already has the version `2` already.

I'm using crm-application 3.1.15 that is the latest stable version released until now.

**Comment by anyt** [comment]
Here is the quote from the documentation:
> Each entity object gets its own history. Therefore, changesets get version numbers starting with 1. Each time a new changeset is created, a new version number is created by incrementing the highest existing version number for a particular entity by one.
https://doc.oroinc.com/backend/entities-data-management/data-audit/#entity-configuration


> I would like to know if I can remove all the version 1 records for those cases that already have the version 2 already.

You could remove all the data audit data if you want to, really 🙂  As the decision to store the data is up to your business requirements. But you should understand that by deleting some records, you will lose the editing history, so you would not be able to use the data audit fully confident. For example, someone could change the entity five times in a row, but by deleting the old versions from history, you will have the record only about the last change, and it will not be consistent with other records anymore.

**Comment by Briones** [comment]
That's very helpful! Thanks for take the time to answer!
