### ISSUE TITLE
How to access filter values in callback function in datagrid

### ISSUE THREAD

**Issue by farzamsabeti** [oroinc/platform#970]
Hello oro team,

Is there a way to access filter values in callback function in datagrid?

I checked `callable: "@oro_email.helper.datagrid.emails->getReadedRowClosure"` and `callable:      ["@oro_workflow.helper.translation", "findTranslation"]` but, I couldn't find a way to access the filter values.

Thanks in advance,
Farzam

**Comment by anyt** [comment]
Hi Farzam,
I suggest creating an event listener to one of the [datagrid events](https://github.com/oroinc/platform/blob/master/src/Oro/Bundle/DataGridBundle/Resources/doc/backend/events.md#build-events).

**Comment by farzamsabeti** [comment]
Hi,

I used `session` in `onBuildBefore` event to pass filter's data to my callback function. It works fine now.

Thank you so much.
