### ISSUE TITLE
Datagrid Inset Mass action parameter for datagrids.

### ISSUE THREAD

**Issue by lmeliberty** [oroinc/platform#971]
Hello all,

Is it possible to disable the parameter "inset" "all" to keep "all visible" and "none" in datagrid options ?

Indeed, my users want the mass action was only launch for "visible rows"

Thanks

![mass_action](https://user-images.githubusercontent.com/8792225/68689248-593f0600-0570-11ea-9dae-b89e080e8f5f.png)

**Comment by anyt** [comment]
Hi @lmeliberty,

Thank you for using the OroPlatform.

The list is defined in an underscore template named [select-all-header-cell.js](https://github.com/oroinc/platform/blob/3.1/src/Oro/Bundle/DataGridBundle/Resources/public/js/datagrid/header-cell/select-all-header-cell.js).

You can override an underscore template in the same way as any other regular JavaScript module, by following [the documentation](https://doc.oroinc.com/frontend/javascript/javascript-modularity/#override-requirejs-modules).

**Comment by lmeliberty** [comment]
Hi @anyt,

Thank you for your anwser.
This solution works well !
