### ISSUE TITLE
Quick question about PHP versions for 4.1

### ISSUE THREAD

**Issue by sadortun** [oroinc/platform#975]
Hi Oro Team,

Quick question for you guys. Will you be supporting `PHP 7.3` and/or `PHP 7.4` for your upcoming  `4.1 LTS` release ?

Have a great day,
Samuel

**Comment by mbessolov** [comment]
PHP 7.3 - yes, right away (4.1.0).
PHP 7.4 - also yes. We didn't check it yet (7.4.0 was releleased just a week ago), so we'll see it we can support it in 4.1.0, or if it will be added in one of the 4.1.x patch releases.

**Comment by sadortun** [comment]
Awesome ! Thanks !

**Comment by Briones** [comment]
So it's supported in 4.1 now that is released?

**Comment by mbessolov** [comment]
@Briones see https://github.com/oroinc/platform/blob/4.1.0/composer.json#L13-L23

**Comment by Briones** [comment]
Thanks! So, it's not supported. There are plans to support it in a future patch release? Just to be sure.

**Comment by mbessolov** [comment]
@Briones what do you mean it is not supported?

**Comment by Briones** [comment]
I miss the `~` symbol, sorry, but thanks for the response!

**Comment by mbessolov** [comment]
Ok, then I'll just restate that:
* PHP 7.3 is supported in 4.1.0 right away. In fact, 4.1.0 *requires* the minimal version of PHP 7.3.13.
* PHP 7.4 - not included in 4.1.0, but it will be added in one of the 4.1.x patch releases (most likely 4.1.1 or 4.1.2).
