### ISSUE TITLE
Advice on upgrading an OroPlatform 1.10 application

### ISSUE THREAD

**Issue by adamlundrigan** [oroinc/platform#980]
I have an application built on OroPlatform 1.10 that I need to either

 1. Upgrade existing codebase to 4.1
 2. Start over from scratch and migrate the data

Should I decide to upgrade rather than replace, my plan is to make a series of versions then deploy them in succession during a downtime window so the database gets migrated properly.  

Do you have any advice on what the minimum set of versions I would need to hop through to get from 1.10 to 4.1 without missing any required database migrations?  From my own research I think this would be the absolute minimum:

1. 1.10.31 --> 3.1.3 (since 3.1.4 removed `upgrade20` tooling)
2. 3.1.3 --> 4.1.0

or would hitting the last/latest release of each major version be a better idea?

1. 1.10.31 --> 2.6.39
2. 2.6.39 --> 3.1.17
3. 3.1.17 --> 4.1.x

**Comment by anyt** [comment]
The upgrade is supported only between LTS versions. 
So you have to upgrade to 2.6, then to 3.1 and finally to 4.1.
