### ISSUE TITLE
Error on assets:build (ERROR in ./bundles/oroui/js/app/services/module-config.js)

### ISSUE THREAD

**Issue by raffaelecarelle** [oroinc/platform#983]
I'm testing version 4.1.0-rc4 and when I run assets:build command, this error occured:
`
ERROR in ./bundles/oroui/js/app/services/module-config.js
    Module not found: Error: Can't resolve 'configs.json' in '/var/www/absolutex.local/public/bundles/oroui/js/app/services'
     @ ./bundles/oroui/js/app/services/module-config.js 6:0-40 28:31-43
     @ ./bundles/oroui/js/app.js
     @ multi whatwg-fetch oroui/js/app oroui/js/app/services/app-ready-load-modules
`

Effectively, at path oroui/js/app/services the file config.json doesn't exist.

**Details about your environment**
- OroPlatform version 4.1.0-rc4
- PHP version: 7.3
- Database MySQL 5.7.29
- node version 12.14.0
- npm version 6.13.4

**Comment by Grygir** [comment]
Hi
`configs.json` -- is generated during webpack config preparation, on a base of declarations from `jsmodules.yml` in `configs` section. Those files are placed in `public/build/configs.json` and `/public/layout-build/{{LAYOUT-NAME}}/configs.json`. Please check if you have `configs.json` files in mentioned places. 

The build dir is one of the places that is used by resolver:
https://github.com/oroinc/platform/blob/master/build/webpack-config-builder/oro-webpack-config.js#L337
