### ISSUE TITLE
Maintenance listener does not work anymore

### ISSUE THREAD

**Issue by hvanoch** [oroinc/platform#993]
**Summary**  
Since https://github.com/oroinc/platform/commit/33885e88007dbda42eac5d984815c1b9c400216e the priority for the onKernelRequest has been changed from 0 to 512. This causes \Lexik\Bundle\MaintenanceBundle\Listener\MaintenanceListener line 197 to always return null. Because the RouterListener of symfony which creates the `_route` attribute has priority 32.
(\Symfony\Component\HttpKernel\KernelEvents line 158)

So that line ALWAYS return null. 
On php 7.4 the next line (part ` '_' === $route[0]`) will even throw an exception. Because you can not get index 0 of a null value.

> Notice: Trying to access array offset on value of type null

On PHP 7.3 this notice is not reported, but still the $route variable always returns null. Which is wrong.

**Steps to reproduce**  
- Install php 7.4
- open any page

**Actual Result**
Exception thrown

**Expected Result**  
no exception

**Details about your environment**
- OroPlatform version: 4.1.1
- PHP version: 7.4
- Database (MySQL, PostgreSQL) version Mysql

**Comment by mbessolov** [comment]
Thank you for reporting this.

(_internal ID: BAP-19693_)

**Comment by anyt** [comment]
Fixed in 4.1.3. Thank you!
